/**
 * ENGENDRÉ — ne pas modifier à la main.
 * Reconstruire avec `pnpm --filter @maioun/frontend run sources`.
 *
 * La table des sources, telle que le collecteur les déclare : un nom lisible,
 * un domaine, et de quoi savoir ce qu'on a le droit d'en faire.
 *
 * `kind` distingue le site PROPRE d'une agence (`localAgency`) du domaine d'un
 * portail. Seul le premier peut servir de logo : celui d'un portail donnerait
 * la même image à des dizaines d'agences distinctes.
 *
 * `domain` est renseigné pour tous, portails compris, parce qu'il sert aussi à
 * RECONNAÎTRE une agence sous ses graphies, et pas seulement à l'illustrer.
 *
 * `logo` n'est renseigné que pour les agences dont l'icône N'EST PAS à
 * `/favicon.ico` — c'est l'adresse que leur site déclare lui-même.
 *
 * `paidContact` marque les sources qui FONT PAYER la mise en relation :
 * l'écran le dit avant le clic, plutôt que de laisser découvrir le péage.
 *
 * `address` est l'adresse de vitrine que l'agence publie, quand on la connaît.
 *
 * `alsoKnownAs` porte les noms sous lesquels les PORTAILS la publient, quand la
 * règle de rapprochement ne peut pas les deviner — « BEP NICE » pour BEP
 * Logement. Relevés sur les annonces, jamais inventés.
 */

export interface SourceInfo {
  readonly name: string;
  readonly domain: string | null;
  /** Famille de la source : seule une `localAgency` a un site bien à elle. */
  readonly kind: 'portal' | 'agencyNetwork' | 'localAgency' | 'aggregator';
  readonly logo: string | null;
  /** La source vend la mise en relation : ses coordonnées ne sont pas libres. */
  readonly paidContact: boolean;
  /** Adresse de la vitrine de l'agence, telle qu'elle la publie. */
  readonly address: {
    readonly street: string;
    readonly postalCode: string;
    readonly city: string;
  } | null;
  /** Les autres noms sous lesquels les portails la publient. */
  readonly alsoKnownAs: readonly string[];
  /** Ses annonces sont les SIENNES : elle ne relaie pas d'agences tierces. */
  readonly publishesOwnListings: boolean;
}

export const SOURCES: Readonly<Record<string, SourceInfo>> = {
  '123loger': {
    name: '123Loger',
    domain: '123loger.com',
    kind: 'portal',
    logo: null,
    paidContact: true,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: true,
  },
  'aa-gestion': {
    name: 'AA Gestion',
    domain: 'aagestion.net',
    kind: 'localAgency',
    logo: 'https://www.aagestion.net/images/favicon.png',
    paidContact: false,
    address: { street: '3 boulevard du Parc Impérial', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'abyla-bosse': {
    name: 'Abyla Bosse',
    domain: 'immobiliere-abc.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2358/media/23981807d6f0268256b02a17c4dfc272.png',
    paidContact: false,
    address: { street: '4 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  acetimo: {
    name: 'Acetimo',
    domain: 'acetimo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/3952/media/95f0170b4d603ca3392ac3b5c458a775.png',
    paidContact: false,
    address: { street: '1 avenue Mirabeau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'acropolis-immo': {
    name: 'Acropolis Immobilier',
    domain: 'acropolisimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku-v2/4050/media/194b024190aaae0b22b1df755c90b24f.png',
    paidContact: false,
    address: { street: '47 rue Arson', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  aequalis: {
    name: 'Aequalis Immobilier',
    domain: 'aequalis-immobilier.com',
    kind: 'localAgency',
    logo: 'https://medias.twimmopro.com/sitemanager/6487339c4ce3873608008354',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  afedim: {
    name: 'AFEDIM',
    domain: 'afedim.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-5-promenade': {
    name: 'Agence 5 Promenade',
    domain: '5promenade.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/445/media/d4cd26018d86f7b26d672bb565d97e5a.png',
    paidContact: false,
    address: { street: '5 promenade des Anglais', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-azureenne': {
    name: 'L’Agence Azuréenne',
    domain: 'lagenceazureenne.com',
    kind: 'localAgency',
    logo: 'https://www.lagenceazureenne.com/images/favicon.png',
    paidContact: false,
    address: { street: '157 avenue de Nice', postalCode: '06800', city: 'Cagnes-sur-Mer' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-californie': {
    name: 'Agence Californie',
    domain: 'agencecalifornie.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '229 avenue de la Californie', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-castel': {
    name: 'Agence Castel',
    domain: 'agencecastel.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '25 rue Bonaparte', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-des-domaines': {
    name: 'Agence des Domaines',
    domain: 'agencedesdomaines.com',
    kind: 'localAgency',
    logo: 'https://www.agencedesdomaines.com/images/favicon.png',
    paidContact: false,
    address: { street: '57 avenue de la Gare', postalCode: '06800', city: 'Cagnes-sur-Mer' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-du-centre': {
    name: 'Agence du Centre',
    domain: 'agenceducentrenice.com',
    kind: 'localAgency',
    logo: 'https://www.agenceducentrenice.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-du-port': {
    name: 'Agence du Port de Nice',
    domain: 'agenceduportdenice.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '28 boulevard Stalingrad', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-dumas': {
    name: 'Agence Dumas',
    domain: 'agencedumas.fr',
    kind: 'localAgency',
    logo: 'https://www.agencedumas.fr/wp-content/uploads/2025/07/cropped-Artboard-1-180x180.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-gounod': {
    name: 'Agence Gounod',
    domain: 'agencegounod.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3348/media/b3eb020e01921a1a037a4e43cd4793d6.jpeg',
    paidContact: false,
    address: { street: '19 rue Gounod', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-longchamp': {
    name: 'Agence Longchamp',
    domain: 'agencelongchamp.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/4750/media/808f85d19582189b003523802646b0bb.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-passy': {
    name: 'Agence Passy',
    domain: 'agencepassy.com',
    kind: 'localAgency',
    logo: 'https://www.agencepassy.com/favicon.png',
    paidContact: false,
    address: { street: '4 place Franklin', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-riviera': {
    name: 'Agence Riviera Real Estate',
    domain: 'agenceriviera.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3520/media/873522a5a86508cd4d104389ac514fcb.png',
    paidContact: false,
    address: { street: '12 rue Cassini', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agence-victoire': {
    name: 'Agence de la Victoire',
    domain: 'agence-victoire-nice.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3308/media/8cf0875ff6203406c7aafb3b48aee96d.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'agent-nicois': {
    name: "L'Agent Niçois",
    domain: 'agentnicois.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/1366/media/fed75df98697547552b96f98b624cfe8.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  agir: {
    name: 'Cabinet A.G.I.R.',
    domain: 'agir.immo',
    kind: 'localAgency',
    logo: 'https://www.agir.immo/images/favicon.png',
    paidContact: false,
    address: { street: '2 rue Maréchal Joffre', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  akorimmo: {
    name: 'AKOR Immo',
    domain: 'akorimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Marui/2825/media/95455d047f076e6236b3213070b1ac21.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  alberti: {
    name: 'Alberti Immobilier',
    domain: 'agencealbertinice.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/3986/media/5d2b1b7eb9ec0af2bf05663c8ccb3257.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'alliance-conseil': {
    name: 'A Alliance Conseil Immobilier',
    domain: 'allianceconseilimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3295/media/807e6eaf70aec148273789ea0ebc0df7.png',
    paidContact: false,
    address: { street: '3 rue Auguste Gal', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'altarea-nice': {
    name: 'Altarea Gestion Immobilière - Nice',
    domain: 'altarea.flatbay.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'am-concept': {
    name: 'AM Concept Patrimoine Immobilier',
    domain: 'amconcept.immo',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'ang-immobilier': {
    name: 'ANG Immobilier',
    domain: 'agence-nice-gambetta.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku-v2/5040/media/afc9709b16ea85ec9bacf1456e98ea22.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'aparte-immobilier': {
    name: 'Aparté Immobilier',
    domain: 'aparte-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Bento/4932/media/da9878917f127ea3f721bdef372a1b1f.png',
    paidContact: false,
    address: { street: '47 rue Rossini', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'api-nice': {
    name: 'API Nice (Azur Patrimoine Immobilier)',
    domain: 'agence-api.com',
    kind: 'localAgency',
    logo: 'https://www.agence-api.com/images/favicon.png',
    paidContact: false,
    address: { street: '3 rue Bavastro', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  appartager: {
    name: 'Appartager',
    domain: 'appartager.com',
    kind: 'portal',
    logo: null,
    paidContact: true,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  arthurimmo: {
    name: 'Arthurimmo.com',
    domain: 'arthurimmo.com',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'ashley-parker': {
    name: 'Ashley & Parker',
    domain: 'ashley-parker.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Mira/3865/media/33894ce038629e5f169c5285b69d9679.png',
    paidContact: false,
    address: { street: '39 rue de France', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  aurus: {
    name: 'Aurus Immobilier',
    domain: 'aurusimmo.com',
    kind: 'localAgency',
    logo: 'https://www.aurusimmo.com/images/favicon.png',
    paidContact: false,
    address: { street: '14 rue du Maréchal Joffre', postalCode: '06310', city: 'Beaulieu-sur-Mer' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'azur-conseil-salmon': {
    name: 'Azur Conseil Salmon',
    domain: 'acsimmo.fr',
    kind: 'localAgency',
    logo: 'https://www.acsimmo.fr/images/favicon.png',
    paidContact: false,
    address: { street: '26 boulevard de Cessole', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  azurimmo: {
    name: 'Azurimmo',
    domain: 'azurimmo06.net',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '170 boulevard Napoléon III', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'barbera-gestion': {
    name: 'Barbera Gestion & Patrimoine',
    domain: 'barbera-gestion.com',
    kind: 'localAgency',
    logo: 'https://www.barbera-gestion.com/theme/img/favicon.png',
    paidContact: false,
    address: { street: '29 avenue Jean Médecin', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  barnes: {
    name: 'BARNES',
    domain: 'barnes-international.com',
    kind: 'agencyNetwork',
    logo: 'https://www.barnes-international.com/accommodation/21/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  bbii: {
    name: 'BBii',
    domain: 'bbii.fr',
    kind: 'localAgency',
    logo: 'https://medias.twimmopro.com/sitemanager/5a9695104ce387066300834d',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  beaumont: {
    name: 'Beaumont Immobilier',
    domain: 'beaumontimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia-v2/3611/media/fb1cb5b04af12286f2f658cebf6745b3.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  belgravia: {
    name: 'Belgravia',
    domain: 'belgravia.fr',
    kind: 'localAgency',
    logo: 'https://www.belgravia.fr/images/favicon.png',
    paidContact: false,
    address: { street: '54 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  bep: {
    name: 'BEP Logement',
    domain: 'bep-logement.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/3796/media/088c6098eacde9385effdd6f1c897bad.png',
    paidContact: false,
    address: null,
    alsoKnownAs: ['BEP Nice', 'BEP Antibes'],
    publishesOwnListings: false,
  },
  'bep-abonnes': {
    name: 'BEP Logement (abonné)',
    domain: 'abonnes.beplogement.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  berenice: {
    name: 'Bérénice Immobilier',
    domain: 'berenice-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.berenice-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  bienici: {
    name: 'Bien’ici',
    domain: 'bienici.com',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'blue-residences': {
    name: 'Blue Résidences',
    domain: 'blue-residences.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3024/media/5775ec396d3a7402aee4e12c40121759.png',
    paidContact: false,
    address: { street: '4 boulevard de Cimiez', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  bomarche: {
    name: 'BôMarché by Lambda Immobilier',
    domain: 'bomarche.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Stax/3961/media/7a05d1272a1418383e7731ac6251a037.png',
    paidContact: false,
    address: { street: '14 avenue Borriglione', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'borne-delaunay': {
    name: 'Borne & Delaunay',
    domain: 'borne-delaunay.com',
    kind: 'localAgency',
    logo: 'https://www.borne-delaunay.com/assets/favicons/favicon-37ada3d02e975cf35351d56695e46cb3f22ebf749f4993a8ca09034ad0d1e1cc.ico',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-central-gestion': {
    name: 'Cabinet Central Gestion',
    domain: 'immobilier-cabinetcentral.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia-v2/3317/media/13c55735ef6710138eb8927df198789a.jpeg',
    paidContact: false,
    address: { street: '24 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-cordier': {
    name: 'Cabinet Cordier',
    domain: 'cabinetcordier.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-europazur': {
    name: 'Cabinet Europazur',
    domain: 'europazur.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/2352/media/4e405ec68e32aa92418d0ae33d513cb0.webp',
    paidContact: false,
    address: { street: '9 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-ledeux': {
    name: 'Cabinet Ledeux Immobilier',
    domain: 'cabinetledeux.com',
    kind: 'localAgency',
    logo: 'https://www.cabinetledeux.com/images/favicon.png',
    paidContact: false,
    address: { street: '15 rue Cassini', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-nardi': {
    name: 'Cabinet Nardi',
    domain: 'cabinetnardi.com',
    kind: 'localAgency',
    logo: 'https://www.cabinetnardi.com/images/favicon.png',
    paidContact: false,
    address: { street: '11 rue Gubernatis', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-reynier': {
    name: 'Cabinet Reynier',
    domain: 'cabinet-reynier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/774/media/23db7352da390575aa22fbce081758ec.png',
    paidContact: false,
    address: { street: '78 boulevard Napoléon III', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cabinet-ventura': {
    name: 'Cabinet Ventura',
    domain: 'cabinetventura.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/2128/media/91c913b968b94bbbdc94dc92d7d15c0d.png',
    paidContact: false,
    address: { street: '61 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cap-sud-immobilier': {
    name: 'Cap Sud Immobilier',
    domain: 'capsud-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Stax/2152/media/c90aa99a4122c183040b30a7ebe0af5e.png',
    paidContact: false,
    address: { street: '256 avenue de la Californie', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  carletta: {
    name: 'Carletta Immobilier',
    domain: 'carletta.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cdc-immobilier': {
    name: 'CDC Immobilier',
    domain: 'cdcimmobilier.com',
    kind: 'localAgency',
    logo: 'https://www.cdcimmobilier.com/favicon.ico',
    paidContact: false,
    address: { street: '2 place Wilson', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cds-gestion': {
    name: 'CDS Gestion',
    domain: 'cdsgestion.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '51 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  cegestim: {
    name: 'Cegestim',
    domain: 'cegestim.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/625/media/2ea9d0a96eb79288d324f84f7aef625a.png',
    paidContact: false,
    address: { street: '8 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  centragence: {
    name: 'Centragence',
    domain: 'centragence.net',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  century21: {
    name: 'Century 21',
    domain: 'century21.fr',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cimiez-boulevard': {
    name: 'Cimiez Boulevard',
    domain: 'cimiez-boulevard.fr',
    kind: 'localAgency',
    logo: 'https://cimiez-boulevard.fr/build/assets/apple-icon-57x57-C4C4tfzi.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  citya: {
    name: 'Citya Immobilier',
    domain: 'citya.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  climmo: {
    name: 'CL Immo Gestion',
    domain: 'climmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/4839/media/ad25e3f8185a5476d50d986669d8b89a.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  coccimmo: {
    name: 'Coccimmo',
    domain: 'coccimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3431/media/3223c52c626127a7187226c08e46c4cb.png',
    paidContact: false,
    address: { street: '143 boulevard René Cassin', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'concept-patrimoine': {
    name: 'Concept Patrimoine Immobilier',
    domain: 'conceptpatrimoine.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  contesso: {
    name: 'Orpi Agence Contesso',
    domain: 'agence-contesso.com',
    kind: 'localAgency',
    logo: 'https://www.agence-contesso.com/images/favicon.png',
    paidContact: false,
    address: { street: '5 avenue des Cigales', postalCode: '06510', city: 'Carros' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  coprogestimmo: {
    name: 'Coprogestimmo',
    domain: 'coprogestimmo.fr',
    kind: 'localAgency',
    logo: 'https://www.coprogestimmo.fr/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cot-ouest': {
    name: "Cot'Ouest Immobilier",
    domain: 'cotouest-immobilier.com',
    kind: 'localAgency',
    logo: 'https://medias.twimmopro.com/sitemanager/69875c06deadd7086509b8e5',
    paidContact: false,
    address: { street: '203 avenue de la Californie', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cote-dazur-properties': {
    name: "Côte d'Azur Properties",
    domain: 'immobilierniceouest.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '2 boulevard Carlone', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'cote-village': {
    name: 'Immobilier Côté Village',
    domain: 'immobilier-cote-village.com',
    kind: 'localAgency',
    logo: 'https://www.immobilier-cote-village.com/images/favicon.png',
    paidContact: false,
    address: { street: '112 boulevard Général de Gaulle', postalCode: '06340', city: 'La Trinité' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'crouzet-breil': {
    name: 'Cabinet Crouzet & Breil',
    domain: 'crouzet-breil.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  dazur: {
    name: "D'Azur Immobilier",
    domain: 'dazur.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3634/media/2b978259236608afead93885b9c806c1.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'de-vita': {
    name: 'De Vita Immobilier',
    domain: 'devita.immo',
    kind: 'localAgency',
    logo: 'https://www.devita.immo/images/favicon.png',
    paidContact: false,
    address: { street: '52 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'delta-promotion': {
    name: 'Delta Promotion',
    domain: 'delta-promotion.com',
    kind: 'localAgency',
    logo: 'https://www.delta-promotion.com/images/favicon.png',
    paidContact: false,
    address: { street: '29 rue Pastorelli', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  dgimmo: {
    name: 'DG Immo',
    domain: 'dgimmo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/3937/media/7428249984622746dc6603480b3ad4dd.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  difimmo: {
    name: 'Diffusion Immobilière',
    domain: 'difimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/4240/media/20b538e888cebe8dc8131bf493630b33.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  dinamy: {
    name: 'Dinamy Immobilier',
    domain: 'dinamyimmobilier.com',
    kind: 'localAgency',
    logo: 'https://dinamyimmobilier.com/Vues/Images/favicon.jpg',
    paidContact: false,
    address: { street: '13 rue François Guisol', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'domi-nice-immobilier': {
    name: 'Domi Nice Immobilier',
    domain: 'dominiceimmobilier.com',
    kind: 'localAgency',
    logo: 'https://www.dominiceimmobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '24 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  drago: {
    name: 'Cabinet Drago',
    domain: 'cabinet-drago.com',
    kind: 'localAgency',
    logo: 'https://www.cabinet-drago.com/favicon.ico',
    paidContact: false,
    address: { street: '29 rue Pastorelli', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  elitimo: {
    name: 'Elitimo',
    domain: 'elitimo.com',
    kind: 'localAgency',
    logo: 'https://medias.twimmopro.com/sitemanager/6973ae990155e634b20ac4e0',
    paidContact: false,
    address: { street: '7 rue de Rivoli', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'email-alerts': {
    name: 'Alertes e-mail',
    domain: 'imap',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  englimmo: {
    name: 'Englimmo',
    domain: 'englimmo.com',
    kind: 'localAgency',
    logo: 'https://www.englimmo.com/images/favicon.png',
    paidContact: false,
    address: { street: '165 avenue de la Californie', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  era: {
    name: 'ERA Immobilier',
    domain: 'eraimmobilier.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'eric-immo': {
    name: 'Eric Immo',
    domain: 'eric-immo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/2188/media/8bda59c5229a4092676925d9f68f5212.jpeg',
    paidContact: false,
    address: { street: '173 boulevard de la Madeleine', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'etude-des-vosges': {
    name: 'Étude des Vosges',
    domain: 'etudedesvosges.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia-v2/3780/media/d368ba414eb252e9434fc40d28f4bf5f.jpeg',
    paidContact: false,
    address: { street: '3 avenue de Saint-Sylvestre', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'etude-lotte': {
    name: 'Étude Lotte',
    domain: 'etudelotte.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia-v2/3489/media/5dabfe9cae641b28decf64b955ab9b2e.jpeg',
    paidContact: false,
    address: { street: '36 avenue Paul Arène', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'fds-carre-dor': {
    name: 'FDS Immobilier Carré d’Or',
    domain: 'fdscarredor.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/3545/media/6c081f4e80eac1541bb2f7c30113fc33.png',
    paidContact: false,
    address: { street: '53 rue de France', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  ferrero: {
    name: 'Agence Ferrero',
    domain: 'ferrero-immobilier.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'figaro-immo': {
    name: 'Figaro Immobilier',
    domain: 'immobilier.lefigaro.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'fit-immobilier': {
    name: 'FIT Immobilier',
    domain: 'fit-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/1705/media/08c2945d04867f779be1e9fa35c57836.png',
    paidContact: false,
    address: { street: '1 avenue de la Lanterne', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'five-stars': {
    name: '5 Stars Holiday House',
    domain: 'fivestarsholidayhouserealestate.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3784/media/60b71498b249d0d63222dc5adf12b7ca.png',
    paidContact: false,
    address: { street: '40 rue de la Buffa', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  fnaim: {
    name: 'FNAIM',
    domain: 'fnaim.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  foncia: {
    name: 'Foncia',
    domain: 'fr.foncia.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  forimmo: {
    name: 'Forimmo',
    domain: 'forimmo.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '31 ter rue Barla', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'french-riviera-studios': {
    name: 'French Riviera Studios',
    domain: 'studios-nice.com',
    kind: 'localAgency',
    logo: 'https://studios-nice.com/wp-content/uploads/2017/04/logo-studio-nice.png',
    paidContact: false,
    address: { street: '2 place Magenta', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'gestion-casa-immo': {
    name: 'Gestion Casa Immobilière',
    domain: 'gestion-casa-immo.com',
    kind: 'localAgency',
    logo: 'https://www.gestion-casa-immo.com/images/favicon.png',
    paidContact: false,
    address: { street: '49 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'gestion-cassini': {
    name: 'Gestion Cassini',
    domain: 'gestioncassini.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/1447/media/bccb3f3c938d4dd71f4cebd1e3d591b0.png',
    paidContact: false,
    address: { street: '12 rue François Guisol', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  gestymo: {
    name: 'Gestymo',
    domain: 'gestymo.com',
    kind: 'localAgency',
    logo: 'https://www.gestymo.com/images/favicon.png',
    paidContact: false,
    address: { street: '375 promenade des Anglais', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  giletta: {
    name: 'Giletta Immobilier',
    domain: 'giletta-properties.com',
    kind: 'localAgency',
    logo: 'https://www.giletta-properties.com/images/favicon.png',
    paidContact: false,
    address: { street: '1 rue Maurice Jaubert', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'grand-metropole': {
    name: 'Grand Métropole',
    domain: 'gdmetropole.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '8 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  griguer: {
    name: 'Cabinet Griguer',
    domain: 'griguer-immobilier.com',
    kind: 'localAgency',
    logo: 'https://griguer-immobilier.com/wp-content/uploads/2019/03/logo-griguer-noir.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'groupe-foch': {
    name: 'Foch Immobilier',
    domain: 'groupe-foch.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3077/media/1e51e8d919dd2e739bdf23b53be3afb2.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'groupe-marshall': {
    name: 'Groupe Marshall',
    domain: 'cabinet-marshall.com',
    kind: 'localAgency',
    logo: 'https://www.cabinet-marshall.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 rue de la Liberté', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'groupe-picado': {
    name: 'Groupe Picado',
    domain: 'groupepicado.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Altera/1953/media/3ae8a26c422ce1325306b929575007c0.png',
    paidContact: false,
    address: { street: '12 avenue Malausséna', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'guy-hoquet': {
    name: 'Guy Hoquet',
    domain: 'guy-hoquet.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'home-on-riviera': {
    name: 'Home on Riviera',
    domain: 'homeonriviera.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3391/media/f8d2efeea6975534a520dbaf9db60fcc.jpeg',
    paidContact: false,
    address: { street: '3 rue Cronstadt', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'home-pearl': {
    name: 'Home Pearl',
    domain: 'homepearl.immo',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku/1095/media/81eda3ccb1d17714e4a45cf175d6ab3a.png',
    paidContact: false,
    address: { street: '16 rue Foncet', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'ici-immobilier': {
    name: 'I.C.I Info Conseil Immobilier',
    domain: 'ici-immobilier.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  igti: {
    name: 'Immobilière GTI',
    domain: 'immobilieregti.com',
    kind: 'localAgency',
    logo: 'https://www.immobilieregti.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-3-points': {
    name: 'Immo 3 Points',
    domain: 'immo3points.fr',
    kind: 'localAgency',
    logo: 'https://www.immo3points.fr/images/favicon.png',
    paidContact: false,
    address: { street: '1 rue Alberti', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-consult-cote-sud': {
    name: 'Immo Consult Côté Sud',
    domain: 'immoconsultcotesud.com',
    kind: 'localAgency',
    logo: 'https://www.immoconsultcotesud.com/images/favicon.png',
    paidContact: false,
    address: { street: '72 avenue d’Estienne d’Orves', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-ideal': {
    name: 'Immo Idéal',
    domain: 'immo-ideal.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '24 avenue de Saint-Sylvestre', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-jbf': {
    name: 'Immo JBF',
    domain: 'immo-jbf.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku/912/media/b88ae62a592b5e4b6c0aceeec4b3607a.jpeg',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-riviera-transactions': {
    name: 'Immo Riviera Transactions',
    domain: 'immoriviera.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immo-sud': {
    name: 'Immo-Sud Nice',
    domain: 'agenceimmosud.com',
    kind: 'localAgency',
    logo: 'https://www.agenceimmosud.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  immo3000: {
    name: 'Immo 3000',
    domain: 'immo3000.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/4391/media/992bc9165e9f2db525987f1660ace316.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  immobilier2nice: {
    name: 'Immobilier 2 Nice',
    domain: 'immobilier2nice.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3397/media/01e84a442ef9682a4d5d8e0cfde98d10.jpeg',
    paidContact: false,
    address: { street: '1 boulevard Auguste Raynaud', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immobiliere-camo': {
    name: 'Immobilière Camo',
    domain: 'immobiliere-camo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/505/media/47f38bc6cca856140f15cef274dbb2ef.jpeg',
    paidContact: false,
    address: { street: '26 rue Arson', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immobiliere-nicoise': {
    name: "L'Immobilière Niçoise",
    domain: 'immobiliere-nicoise.com',
    kind: 'localAgency',
    logo: 'https://www.immobiliere-nicoise.com/images/favicon.png',
    paidContact: false,
    address: { street: '33 avenue du Maréchal Foch', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'immobiliere-pelou': {
    name: 'Immobilière Pelou',
    domain: 'immobiliere-pelou.com',
    kind: 'localAgency',
    logo: 'https://www.immobiliere-pelou.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  immojeune: {
    name: 'ImmoJeune',
    domain: 'immojeune.com',
    kind: 'portal',
    logo: 'https://www.immojeune.com/img/logo.svg',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: true,
  },
  imodirect: {
    name: 'Imodirect',
    domain: 'annonces.imodirect.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  inli: {
    name: "In'li",
    domain: 'inli.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'isit-immobilier': {
    name: 'ISIT Immobilier',
    domain: 'isitimmo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3726/media/97e7038b1a7bc3c48e202e8089c35fd2.jpeg',
    paidContact: false,
    address: { street: '26 rue de la Buffa', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'john-taylor': {
    name: 'John Taylor',
    domain: 'john-taylor.fr',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'joseph-garnier': {
    name: 'Joseph Garnier Real Estate',
    domain: 'josephgarnier.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku-v2/1900/media/e585caef42fc2be6caa6b9ece5c6b976.png',
    paidContact: false,
    address: { street: '6 boulevard Joseph Garnier', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'kalliste-immo-conseil': {
    name: 'Kalliste Immo Conseil',
    domain: 'kalliste-immo-conseil.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/1290/media/22271bc09b36f04c68b5bd03d100850b.png',
    paidContact: false,
    address: { street: '27 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  kapera: {
    name: 'Kapera Immobilier',
    domain: 'kapera-immobilier.com',
    kind: 'localAgency',
    logo: 'https://kapera-immobilier.com/wp-content/uploads/2025/11/cropped-favicon-kapera-e1763558177530-180x180.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'keller-williams': {
    name: 'Keller Williams',
    domain: 'kwfrance.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-chouette': {
    name: 'La Chouette Agence Immobilière',
    domain: 'lachouette.immo',
    kind: 'localAgency',
    logo: 'https://www.lachouette.immo/images/favicon.png',
    paidContact: false,
    address: { street: '3 place Pellegrini', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-clef-immobiliere': {
    name: 'La Clef Immobilière',
    domain: 'laclefimmobiliere.com',
    kind: 'localAgency',
    logo: 'https://www.laclefimmobiliere.com/images/favicon.png',
    paidContact: false,
    address: { street: '24 boulevard Saint-Roch', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-conca-dor': {
    name: 'La Conca d’Or',
    domain: 'laconcador.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia-v2/3959/media/67a059b1de2ab49cbf93c9a4af10b11e.png',
    paidContact: false,
    address: { street: '466 boulevard Léon Sauvan', postalCode: '06690', city: 'Tourrette-Levens' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-firme': {
    name: 'La Firme',
    domain: 'proazurdagasso.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Bento/4826/media/b71d64404ce83e62d9f3b92e2f770205.png',
    paidContact: false,
    address: { street: '12 rue Gioffredo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-franco-suisse': {
    name: 'La Franco Suisse',
    domain: 'lafrancosuisse.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: "19 rue de l'Hôtel des Postes", postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-perouse': {
    name: 'La Pérouse Immobilier',
    domain: 'laperouse-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2399/media/766bb68166a5aadf03762b9ce260f89e.png',
    paidContact: false,
    address: { street: '17 rue Alfred Mortier', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'la-petite-maison': {
    name: 'La Petite Maison',
    domain: 'la-petitemaison.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/2562/media/f964696a35f2fea3d8da7de3ec4aa3b8.png',
    paidContact: false,
    address: { street: '301 chemin de la Ginestière', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  ladresse: {
    name: "L'Adresse",
    domain: 'ladresse.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  laforet: {
    name: 'Laforêt',
    domain: 'laforet.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'lagence-jean-jaures': {
    name: 'L’Agence Jean Jaurès',
    domain: 'l-agence.fr',
    kind: 'localAgency',
    logo: 'https://www.l-agence.fr/images/favicon.png',
    paidContact: false,
    address: { street: '48 boulevard Jean Jaurès', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  lamy: {
    name: 'Lamy Immobilier',
    domain: 'lamy-immobilier.fr',
    kind: 'agencyNetwork',
    logo: 'https://www.lamy-immobilier.fr/assets/build/images/favicon/apple-touch-icon.7031a2e5.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  lapierre: {
    name: 'Anne-Sophie Lapierre Immobilier',
    domain: 'lapierre-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.lapierre-immobilier.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'lb-immobilier': {
    name: 'L&B Immobilier',
    domain: 'lb-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://www.lb-immobilier.fr/images/favicon.png',
    paidContact: false,
    address: { street: '4 avenue de Verdun', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'leprince-realty': {
    name: 'leprince realty',
    domain: 'leprincerealty.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone-v2/4246/media/bb174d6a430b2ebeaf6430c6cfa2e3b2.webp',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  lesiteimmo: {
    name: 'LeSiteImmo',
    domain: 'lesiteimmo.com',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'liberty-agency': {
    name: 'Liberty Agency',
    domain: 'agence-liberty.com',
    kind: 'localAgency',
    logo: 'https://www.agence-liberty.com/images/favicon.png',
    paidContact: false,
    address: { street: '136 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  lienhard: {
    name: 'Lienhard Immo',
    domain: 'lienhardimmo.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  locservice: {
    name: 'LocService',
    domain: 'locservice.fr',
    kind: 'portal',
    logo: null,
    paidContact: true,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: true,
  },
  lodgis: {
    name: 'Lodgis',
    domain: 'lodgis.com',
    kind: 'agencyNetwork',
    logo: 'https://www.lodgis.com/rsrc/blue/favicon.ico?v=1765270423',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  loquis: {
    name: 'Cabinet Loquis',
    domain: 'loquis.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '3 place Alexandre Médecin', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'lt-immobilier': {
    name: 'LT Immobilier',
    domain: 'lt-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.lt-immobilier.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  lumina: {
    name: 'Lumina Immobilier',
    domain: 'lumina-immo.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'maison-k': {
    name: 'Maison K Immobilier',
    domain: 'maisonk-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3806/media/a6bdeae23eef4210b0b5054fce2d7721.png',
    paidContact: false,
    address: { street: '3 place Masséna', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'maison-quatre': {
    name: 'Maison Quatre',
    domain: 'maisonquatre.la-boite-immo.com',
    kind: 'localAgency',
    logo: 'https://maisonquatre.la-boite-immo.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 rue Dalpozzo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  maisonette: {
    name: 'Maisonette',
    domain: 'lamaisonette.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  marcele: {
    name: 'Marcele Immobilier',
    domain: 'ballestri-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/3461/media/cc89eba61f1bda47326f16ea54960ca4.jpeg',
    paidContact: false,
    address: { street: '2 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'marchal-immobilier': {
    name: 'Marchal Immobilier',
    domain: 'marchal-immobilier.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '83 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'marro-immobilier': {
    name: 'Cabinet Marro Immobilier',
    domain: 'marro-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.marro-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '41 boulevard Pierre Sola', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'massena-immo': {
    name: 'Masséna Immobilier',
    domain: 'massena-immo.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3620/media/6e98366ef367546b36d867b32fdabb35.jpeg',
    paidContact: false,
    address: { street: '12 avenue Félix Faure', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'mediterranee-immo': {
    name: 'Méditerranée Immo',
    domain: 'mediterranee-immo.fr',
    kind: 'localAgency',
    logo: 'https://www.mediterranee-immo.fr/images/favicon.png',
    paidContact: false,
    address: { street: '20 avenue Valombrose', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  midem: {
    name: 'Midem Immobilier',
    domain: 'midem-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://www.midem-immobilier.fr/images/favicon.png',
    paidContact: false,
    address: { street: '8 avenue Saint-Augustin', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'milor-immobilier': {
    name: 'Milor Immobilier',
    domain: 'milorimmobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/2902/media/36888d381f56038c397c82742c0f9d70.png',
    paidContact: false,
    address: { street: '50 boulevard Joseph Garnier', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  mirabello: {
    name: 'Mirabello Immobilier',
    domain: 'mirabello-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/1119/media/9b83801aef3ae2f9e99960813b8a2de4.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  miramar: {
    name: 'Miramar Real Estate',
    domain: 'miramarimmo.com',
    kind: 'localAgency',
    logo: 'https://miramarimmo.com/wp-content/uploads/2025/11/cropped-faviconMiramra-180x180.png',
    paidContact: false,
    address: { street: '7/13 boulevard Franck Pilatte', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'mk-immo': {
    name: 'MK Immo',
    domain: 'mk-immo.fr',
    kind: 'localAgency',
    logo: 'https://medias.twimmopro.com/sitemanager/698f56917f8f97acb6049d42',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  morningcroissant: {
    name: 'MorningCroissant',
    domain: 'morningcroissant.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: true,
  },
  'moss-immobilier': {
    name: 'Moss Immobilier',
    domain: 'mossimmobilier.com',
    kind: 'localAgency',
    logo: 'https://mossimmobilier.com/wp-content/uploads/2025/12/cropped-cropped-petit-logo-moss-immobilier-180x180.webp',
    paidContact: false,
    address: { street: '2 rue Beethoven', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  murta: {
    name: 'Murta Immobilier',
    domain: 'murta-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.murta-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '23 bis avenue Général de Gaulle', postalCode: '06340', city: 'Drap' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'nestenn-nice-port': {
    name: 'Nestenn Nice Port - Riquier',
    domain: 'immobilier-nice-port.nestenn.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '18 boulevard de Riquier', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'nice-premium': {
    name: 'Nice Premium Immobilier',
    domain: 'nice-premium-immobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2767/media/d372d915d8ebfe5ac050132e4125c7b0.png',
    paidContact: false,
    address: { street: '21 rue Michel-Ange', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'nicolas-pisani': {
    name: 'Nicolas Pisani Real Estate',
    domain: 'nicolaspisani.com',
    kind: 'localAgency',
    logo: 'https://www.nicolaspisani.com/specific_images/favicon.ico',
    paidContact: false,
    address: { street: '1 rue Paul Doumer', postalCode: '06310', city: 'Beaulieu-sur-Mer' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  norait: {
    name: 'Norait Immobilier',
    domain: 'norait-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/1033/media/c6ec75c40128c8bf78ddcd682e4d8c15.png',
    paidContact: false,
    address: { street: '20 rue Verdi', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  nousgerons: {
    name: 'NousGérons',
    domain: 'nousgerons.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  optimmo: {
    name: 'Optimmo',
    domain: 'groupe-optimmo.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  oqoro: {
    name: 'Oqoro',
    domain: 'oqoro.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  orea: {
    name: 'Oréa Immobilier',
    domain: 'orea-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/1517/media/9b04900077fdd4c400d9bdc514997912.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'orientation-immobiliere': {
    name: 'L’Orientation Immobilière',
    domain: 'orimnice.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '76 avenue de Brancolar', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  orpi: {
    name: 'Orpi',
    domain: 'orpi.com',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'palais-immobilier': {
    name: 'Palais Immobilier',
    domain: 'palaisimmobilier.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/1929/media/d8685ce4a87bf1396cb1a6eb5f720ffb.jpeg',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  pap: {
    name: 'PAP',
    domain: 'pap.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'parnasse-immobilier': {
    name: 'Parnasse Immobilier',
    domain: 'parnasse-immobilier.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '10 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'partners-immo': {
    name: 'Partners Immo',
    domain: 'partners-immo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2919/media/0e78952c85a99824121bec7557a663b4.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  paruvendu: {
    name: 'ParuVendu',
    domain: 'paruvendu.fr',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  personalimmo: {
    name: 'Personal Immo',
    domain: 'personalimmo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2839/media/34b55a6c2edd556f155ae47397c8b38b.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  petrova: {
    name: 'Petrova Investissement Immobilier',
    domain: 'petrovainvestissement.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/1908/media/0fe7c39fcba07adfc73ffca8b8fcf836.png',
    paidContact: false,
    address: { street: '5 bis quai Rauba Capeu', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'phoenix-glv': {
    name: 'Phoenix GLV',
    domain: 'phoenix-glv.com',
    kind: 'localAgency',
    logo: 'https://www.phoenix-glv.com/images/favicon.png',
    paidContact: false,
    address: { street: '455 promenade des Anglais', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'pht-real-estate': {
    name: 'PHT Real Estate',
    domain: 'phtrealestate.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Mira/3973/media/c756cab8153d65a43930a052e3a22522.png',
    paidContact: false,
    address: { street: '15 rue Biscarra', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'platine-immobilier': {
    name: 'Platine Immobilier',
    domain: 'platineimmobilier.eu',
    kind: 'localAgency',
    logo: 'https://www.platineimmobilier.eu/images/favicon.png',
    paidContact: false,
    address: { street: '5 rue Blacas', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  postillon: {
    name: 'Postillon Immobilier',
    domain: 'postillon-immobilier.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/548/media/e94bb992d5c019c1b244169bdce7e7f6.jpeg',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  privilege: {
    name: 'Agence Privilège',
    domain: 'agenceprivilege.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/803/media/edd34909fa67936a92ba460a5d2bf92a.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  procivis: {
    name: 'Immo de France Côte d’Azur',
    domain: 'procivis.fr',
    kind: 'agencyNetwork',
    logo: 'https://www.procivis.fr/assets/favicon-cd40c9e7.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  provencalpes: {
    name: 'Provencalpes',
    domain: 'provencalpes.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/1800/media/8c81d88fb722abb9151802dec96b0c1b.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  pujol: {
    name: 'Immobilière Pujol',
    domain: 'immobiliere-pujol.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '7 rue du Dr Fiolle', postalCode: '13006', city: 'Marseille' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  rentola: {
    name: 'Rentola',
    domain: 'rentola.fr',
    kind: 'portal',
    logo: 'https://rentola.fr/theme/logo/logo-default.svg',
    paidContact: true,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  rentumo: {
    name: 'Rentumo',
    domain: 'rentumo.com',
    kind: 'aggregator',
    logo: null,
    paidContact: true,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  repimmo: {
    name: 'Repimmo',
    domain: 'repimmo.com',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'resid-immo': {
    name: 'Resid’Immo',
    domain: 'residimmo.fr',
    kind: 'localAgency',
    logo: 'https://www.residimmo.fr/images/favicon.png',
    paidContact: false,
    address: { street: '900 boulevard du Mercantour', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'reussite-immo': {
    name: 'Réussite Immo Nice',
    domain: 'immonice06.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/1654/media/0bb36cb43e6ef22de407233c12162a40.jpeg',
    paidContact: false,
    address: { street: '6 rue Massenet', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'reutter-invest': {
    name: 'Reutter Invest',
    domain: 'reutterinvest.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Elone/3640/media/bbeb303df356ddb664cb38dfde6c64f7.png',
    paidContact: false,
    address: { street: '45 rue Rossini', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'richer-immobilier': {
    name: 'Richer Immobilier',
    domain: 'richerimmobilier.com',
    kind: 'localAgency',
    logo: 'https://www.richerimmobilier.com/wp-content/uploads/2021/04/cropped-favicon-richerimmo-180x180.jpg',
    paidContact: false,
    address: { street: '50 boulevard Stalingrad', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'riviera-angels': {
    name: 'Riviera Angels Immobilier',
    domain: 'riviera-angels.com',
    kind: 'localAgency',
    logo: 'https://www.riviera-angels.com/images/favicon.png',
    paidContact: false,
    address: { street: '50 rue de France', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'riviera-concept': {
    name: 'Riviera Concept',
    domain: 'rivieraconcept.com',
    kind: 'localAgency',
    logo: 'https://www.rivieraconcept.com/images/favicon.png',
    paidContact: false,
    address: { street: '67 rue Rossini', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'riviera-sud-immobilier': {
    name: 'Riviera Sud Immobilier',
    domain: 'rsi-immo.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '5 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  roseland: {
    name: 'Immobilière Roseland',
    domain: 'immobiliereroseland.fr',
    kind: 'localAgency',
    logo: 'https://www.immobiliereroseland.fr/images/favicon.png',
    paidContact: false,
    address: { street: '38 rue Auguste Gal', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  safi: {
    name: 'SAFI Méditerranée',
    domain: 'safimediterranee.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'sag-immobilier': {
    name: 'SAG Immobilier',
    domain: 'sag-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.sag-immobilier.com/images/favicon.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'saint-roch': {
    name: 'Saint Roch Immobilier',
    domain: 'saintrochimmobilier.com',
    kind: 'localAgency',
    logo: 'https://saintrochimmobilier.com/images/favicon.ico',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  sambroni: {
    name: 'Sambroni Immobilier',
    domain: 'agencesambroni.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Mira-v2/4723/media/d5d3d1044e9885f2b2144d9d52d3abc6.png',
    paidContact: false,
    address: { street: '186 avenue de Pessicart', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'savi-esteve': {
    name: 'Agence Savi Estève',
    domain: 'saviesteve-nice.com',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '24 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  solissimmo: {
    name: 'Solissimmo',
    domain: 'solissimmo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Altera/2059/media/c9818b2edc2c310cab0402119efa883c.png',
    paidContact: false,
    address: { street: '30 rue Alphonse Karr', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'square-habitat': {
    name: 'Square Habitat',
    domain: 'squarehabitat.fr',
    kind: 'agencyNetwork',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'street-immobilier': {
    name: 'Street Immobilier',
    domain: 'street-immobilier.com',
    kind: 'localAgency',
    logo: 'https://street-immobilier.com/elements/img/logo.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  studapart: {
    name: 'Studapart',
    domain: 'studapart.com',
    kind: 'portal',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: true,
  },
  'sud-agence': {
    name: 'Sud Agence',
    domain: 'sudagence.fr',
    kind: 'localAgency',
    logo: 'https://www.sudagence.fr/images/favicon.png',
    paidContact: false,
    address: { street: '25 rue Arson', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'sud-contact': {
    name: 'Sud Contact Immobilier',
    domain: 'nice-ouest-immobilier.com',
    kind: 'localAgency',
    logo: 'https://www.nice-ouest-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '46 avenue Saint-Augustin', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'sun-immobilia': {
    name: 'Sun Immobilia',
    domain: 'sunimmobilia.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  tichadou: {
    name: 'Immobilière Tichadou',
    domain: 'tichadou.fr',
    kind: 'localAgency',
    logo: null,
    paidContact: false,
    address: { street: '2 rue du Congrès', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'tosca-nice-le-port': {
    name: 'Agence Tosca Nice le Port',
    domain: 'agencetosca.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Zenia/1689/media/a42e1905b0289066132566cf389cdaf5.png',
    paidContact: false,
    address: { street: '13 rue Cassini', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  transactimo: {
    name: 'Transactimo',
    domain: 'transactimo-nice.com',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Haku-v2/4147/media/d4cef05e44c2cd39271ddbd7e4785079.png',
    paidContact: false,
    address: { street: '19 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'valrose-immobilier': {
    name: 'Valrose Immobilier',
    domain: 'valrose-immo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/2235/media/12814af4ee3e53a48172d89910cd2737.png',
    paidContact: false,
    address: { street: '108 avenue Saint-Lambert', postalCode: '06100', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'victor-hugo': {
    name: 'Immobilière Victor Hugo',
    domain: 'immobilierevictorhugo.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Cello/1329/media/870f0958a98b6cfe0d2609d2fe970d6d.png',
    paidContact: false,
    address: { street: '15 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  vizcaya: {
    name: 'Vizcaya Immobilier',
    domain: 'vizcaya.fr',
    kind: 'localAgency',
    logo: 'https://d36vnx92dgl2c5.cloudfront.net/prod/Mira-v2/4721/media/3cc1639c0669a1e6c7b54191409f0de2.png',
    paidContact: false,
    address: { street: '4 quai Papacino', postalCode: '06300', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  'votre-agence-immo': {
    name: 'Votre Agence Immo',
    domain: 'votre-agence-immo.fr',
    kind: 'localAgency',
    logo: 'https://votre-agence-immo.fr/wp-content/themes/votreagenceimmo/img/icons/touch.png',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  westimmo: {
    name: 'Westimmo',
    domain: 'westimmo-properties.com',
    kind: 'localAgency',
    logo: 'https://www.westimmo-properties.com/images/favicon.png',
    paidContact: false,
    address: { street: '200 avenue de la Californie', postalCode: '06200', city: 'Nice' },
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
  winter: {
    name: 'Winter Immobilier',
    domain: 'agence-winter.com',
    kind: 'localAgency',
    logo: 'https://www.agence-winter.com/favicons/favicon.ico',
    paidContact: false,
    address: null,
    alsoKnownAs: [],
    publishesOwnListings: false,
  },
};
