/**
 * ENGENDRÉ — ne pas modifier à la main.
 * Reconstruire avec `pnpm --filter @maioun/frontend run sources`.
 *
 * La table des sources, telle que le collecteur les déclare : un nom lisible et,
 * pour les agences qui ont leur propre site, son domaine.
 *
 * `domain` vaut `null` pour les portails : leur domaine n'est pas celui d'une
 * agence, et s'en servir comme logo donnerait la même image à des dizaines
 * d'agences distinctes.
 *
 * `logo` n'est renseigné que pour les agences dont l'icône N'EST PAS à
 * `/favicon.ico` — c'est l'adresse que leur site déclare lui-même.
 *
 * `paidContact` marque les sources qui FONT PAYER la mise en relation :
 * l'écran le dit avant le clic, plutôt que de laisser découvrir le péage.
 */

export interface SourceInfo {
  readonly name: string;
  readonly domain: string | null;
  readonly logo: string | null;
  /** La source vend la mise en relation : ses coordonnées ne sont pas libres. */
  readonly paidContact: boolean;
}

export const SOURCES: Readonly<Record<string, SourceInfo>> = {
  'aa-gestion': {
    name: 'AA Gestion',
    domain: 'aagestion.net',
    logo: 'https://www.aagestion.net/images/favicon.png',
    paidContact: false,
  },
  'acropolis-immo': {
    name: 'Acropolis Immobilier',
    domain: 'acropolisimmo.com',
    logo: null,
    paidContact: false,
  },
  afedim: { name: 'AFEDIM', domain: 'afedim.fr', logo: null, paidContact: false },
  'agence-des-domaines': {
    name: 'Agence des Domaines',
    domain: 'agencedesdomaines.com',
    logo: 'https://www.agencedesdomaines.com/images/favicon.png',
    paidContact: false,
  },
  'agence-du-centre': {
    name: 'Agence du Centre',
    domain: 'agenceducentrenice.com',
    logo: 'https://www.agenceducentrenice.com/images/favicon.png',
    paidContact: false,
  },
  'agence-longchamp': {
    name: 'Agence Longchamp',
    domain: 'agencelongchamp.com',
    logo: null,
    paidContact: false,
  },
  'agence-passy': {
    name: 'Agence Passy',
    domain: 'agencepassy.com',
    logo: 'https://www.agencepassy.com/favicon.png',
    paidContact: false,
  },
  'agence-riviera': {
    name: 'Agence Riviera Real Estate',
    domain: 'agenceriviera.com',
    logo: null,
    paidContact: false,
  },
  'agence-victoire': {
    name: 'Agence de la Victoire',
    domain: 'agence-victoire-nice.com',
    logo: null,
    paidContact: false,
  },
  'agent-nicois': {
    name: "L'Agent Niçois",
    domain: 'agentnicois.com',
    logo: null,
    paidContact: false,
  },
  agir: {
    name: 'Cabinet AGIR',
    domain: 'agir.immo',
    logo: 'https://www.agir.immo/images/favicon.png',
    paidContact: false,
  },
  akorimmo: { name: 'AKOR Immo', domain: 'akorimmo.com', logo: null, paidContact: false },
  alberti: {
    name: 'Alberti Immobilier',
    domain: 'agencealbertinice.com',
    logo: null,
    paidContact: false,
  },
  'alliance-conseil': {
    name: 'A Alliance Conseil Immobilier',
    domain: 'allianceconseilimmo.com',
    logo: null,
    paidContact: false,
  },
  'am-concept': {
    name: 'AM Concept Patrimoine Immobilier',
    domain: 'amconcept.immo',
    logo: null,
    paidContact: false,
  },
  'ang-immobilier': {
    name: 'ANG Immobilier',
    domain: 'agence-nice-gambetta.fr',
    logo: null,
    paidContact: false,
  },
  arthurimmo: { name: 'Arthurimmo.com Nice', domain: null, logo: null, paidContact: false },
  'ashley-parker': {
    name: 'Ashley & Parker',
    domain: 'ashley-parker.fr',
    logo: null,
    paidContact: false,
  },
  aurus: {
    name: 'Aurus Immobilier',
    domain: 'aurusimmo.com',
    logo: 'https://www.aurusimmo.com/images/favicon.png',
    paidContact: false,
  },
  beaumont: {
    name: 'Beaumont Immobilier',
    domain: 'beaumontimmo.com',
    logo: null,
    paidContact: false,
  },
  belgravia: {
    name: 'Belgravia',
    domain: 'belgravia.fr',
    logo: 'https://www.belgravia.fr/images/favicon.png',
    paidContact: false,
  },
  bep: { name: 'BEP Logement', domain: 'bep-logement.com', logo: null, paidContact: false },
  'bep-abonnes': { name: 'BEP Logement (abonné)', domain: null, logo: null, paidContact: false },
  berenice: {
    name: 'Bérénice Immobilier',
    domain: 'berenice-immobilier.com',
    logo: 'https://www.berenice-immobilier.com/images/favicon.png',
    paidContact: false,
  },
  bienici: { name: 'Bien’ici', domain: null, logo: null, paidContact: false },
  bomarche: {
    name: 'BôMarché by Lambda Immobilier',
    domain: 'bomarche.fr',
    logo: null,
    paidContact: false,
  },
  'borne-delaunay': {
    name: 'Borne & Delaunay',
    domain: 'borne-delaunay.com',
    logo: null,
    paidContact: false,
  },
  'cabinet-cordier': {
    name: 'Cabinet Cordier',
    domain: 'cabinetcordier.com',
    logo: null,
    paidContact: false,
  },
  'cabinet-nardi': {
    name: 'Cabinet Nardi',
    domain: 'cabinetnardi.com',
    logo: 'https://www.cabinetnardi.com/images/favicon.png',
    paidContact: false,
  },
  'cabinet-reynier': {
    name: 'Cabinet Reynier',
    domain: 'cabinet-reynier.com',
    logo: null,
    paidContact: false,
  },
  'cabinet-ventura': {
    name: 'Cabinet Ventura',
    domain: 'cabinetventura.com',
    logo: null,
    paidContact: false,
  },
  carletta: { name: 'Carletta Immobilier', domain: 'carletta.fr', logo: null, paidContact: false },
  centragence: { name: 'Centragence', domain: 'centragence.net', logo: null, paidContact: false },
  century21: { name: 'Century 21', domain: null, logo: null, paidContact: false },
  'cimiez-boulevard': {
    name: 'Cimiez Boulevard',
    domain: 'cimiez-boulevard.fr',
    logo: 'https://cimiez-boulevard.fr/build/assets/apple-icon-57x57-C4C4tfzi.png',
    paidContact: false,
  },
  citya: { name: 'Citya Immobilier', domain: null, logo: null, paidContact: false },
  climmo: { name: 'CL Immo Gestion', domain: 'climmo.com', logo: null, paidContact: false },
  'concept-patrimoine': {
    name: 'Concept Patrimoine',
    domain: 'conceptpatrimoine.fr',
    logo: null,
    paidContact: false,
  },
  contesso: {
    name: 'Orpi Agence Contesso',
    domain: 'agence-contesso.com',
    logo: 'https://www.agence-contesso.com/images/favicon.png',
    paidContact: false,
  },
  coprogestimmo: {
    name: 'Coprogestimmo',
    domain: 'coprogestimmo.fr',
    logo: 'https://www.coprogestimmo.fr/images/favicon.png',
    paidContact: false,
  },
  'cote-village': {
    name: 'Immobilier Côté Village',
    domain: 'immobilier-cote-village.com',
    logo: 'https://www.immobilier-cote-village.com/images/favicon.png',
    paidContact: false,
  },
  'crouzet-breil': {
    name: 'Cabinet Crouzet & Breil',
    domain: 'crouzet-breil.com',
    logo: null,
    paidContact: false,
  },
  dazur: { name: "D'Azur Immobilier", domain: 'dazur.fr', logo: null, paidContact: false },
  'de-vita': {
    name: 'De Vita Immobilier',
    domain: 'devita.immo',
    logo: 'https://www.devita.immo/images/favicon.png',
    paidContact: false,
  },
  dgimmo: { name: 'DG Immo', domain: 'dgimmo.fr', logo: null, paidContact: false },
  difimmo: { name: 'Diffusion Immobilière', domain: 'difimmo.com', logo: null, paidContact: false },
  dinamy: {
    name: 'Dinamy Immobilier',
    domain: 'dinamyimmobilier.com',
    logo: 'https://dinamyimmobilier.com/Vues/Images/favicon.jpg',
    paidContact: false,
  },
  drago: { name: 'Cabinet Drago', domain: 'cabinet-drago.com', logo: null, paidContact: false },
  'email-alerts': { name: 'Alertes e-mail', domain: null, logo: null, paidContact: false },
  era: { name: 'ERA Immobilier', domain: null, logo: null, paidContact: false },
  'etude-lotte': { name: 'Étude Lotte', domain: 'etudelotte.com', logo: null, paidContact: false },
  'fds-carre-dor': {
    name: 'FDS Immobilier Carré d’Or',
    domain: 'fdscarredor.com',
    logo: null,
    paidContact: false,
  },
  ferrero: {
    name: 'Agence Ferrero',
    domain: 'ferrero-immobilier.fr',
    logo: null,
    paidContact: false,
  },
  'fit-immobilier': {
    name: 'FIT Immobilier',
    domain: 'fit-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'five-stars': {
    name: '5 Stars Holiday House',
    domain: 'fivestarsholidayhouserealestate.com',
    logo: null,
    paidContact: false,
  },
  fnaim: { name: 'FNAIM', domain: null, logo: null, paidContact: false },
  foncia: { name: 'Foncia', domain: null, logo: null, paidContact: false },
  'gestion-cassini': {
    name: 'Gestion Cassini',
    domain: 'gestioncassini.com',
    logo: null,
    paidContact: false,
  },
  giletta: {
    name: 'Giletta Immobilier',
    domain: 'giletta-properties.com',
    logo: 'https://www.giletta-properties.com/images/favicon.png',
    paidContact: false,
  },
  griguer: {
    name: 'Cabinet Griguer',
    domain: 'griguer-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'groupe-foch': {
    name: 'Foch Immobilier',
    domain: 'groupe-foch.com',
    logo: null,
    paidContact: false,
  },
  'groupe-marshall': {
    name: 'Groupe Marshall',
    domain: 'cabinet-marshall.com',
    logo: 'https://www.cabinet-marshall.com/images/favicon.png',
    paidContact: false,
  },
  'groupe-picado': {
    name: 'Groupe Picado',
    domain: 'groupepicado.com',
    logo: null,
    paidContact: false,
  },
  'home-pearl': { name: 'Home Pearl', domain: 'homepearl.immo', logo: null, paidContact: false },
  'ici-immobilier': {
    name: 'I.C.I Info Conseil Immobilier',
    domain: 'ici-immobilier.com',
    logo: null,
    paidContact: false,
  },
  igti: { name: 'Immobilière GTI', domain: 'immobilieregti.com', logo: null, paidContact: false },
  'immo-consult-cote-sud': {
    name: 'Immo Consult Côté Sud',
    domain: 'immoconsultcotesud.com',
    logo: 'https://www.immoconsultcotesud.com/images/favicon.png',
    paidContact: false,
  },
  'immo-jbf': { name: 'Immo JBF', domain: 'immo-jbf.com', logo: null, paidContact: false },
  'immo-sud': {
    name: 'Immo-Sud Nice',
    domain: 'agenceimmosud.com',
    logo: 'https://www.agenceimmosud.com/images/favicon.png',
    paidContact: false,
  },
  immo3000: { name: 'Immo 3000', domain: 'immo3000.com', logo: null, paidContact: false },
  immobilier2nice: {
    name: 'Immobilier 2 Nice',
    domain: 'immobilier2nice.com',
    logo: null,
    paidContact: false,
  },
  'immobiliere-nicoise': {
    name: "L'Immobilière Niçoise",
    domain: 'immobiliere-nicoise.com',
    logo: 'https://www.immobiliere-nicoise.com/images/favicon.png',
    paidContact: false,
  },
  'immobiliere-pelou': {
    name: 'Immobilière Pelou',
    domain: 'immobiliere-pelou.com',
    logo: 'https://www.immobiliere-pelou.com/images/favicon.png',
    paidContact: false,
  },
  inli: { name: "In'li", domain: 'inli.fr', logo: null, paidContact: false },
  'joseph-garnier': {
    name: 'Joseph Garnier Real Estate',
    domain: 'josephgarnier.fr',
    logo: null,
    paidContact: false,
  },
  kapera: {
    name: 'Kapera Immobilier',
    domain: 'kapera-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'la-conca-dor': {
    name: 'La Conca d’Or',
    domain: 'laconcador.com',
    logo: null,
    paidContact: false,
  },
  'la-firme': { name: 'La Firme', domain: 'proazurdagasso.com', logo: null, paidContact: false },
  ladresse: { name: "L'Adresse", domain: 'ladresse.com', logo: null, paidContact: false },
  laforet: { name: 'Laforêt', domain: null, logo: null, paidContact: false },
  lamy: { name: 'Lamy Immobilier', domain: null, logo: null, paidContact: false },
  lapierre: {
    name: 'Anne-Sophie Lapierre Immobilier',
    domain: 'lapierre-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'lb-immobilier': {
    name: 'L&B Immobilier',
    domain: 'lb-immobilier.fr',
    logo: 'https://www.lb-immobilier.fr/images/favicon.png',
    paidContact: false,
  },
  'leprince-realty': {
    name: 'leprince realty',
    domain: 'leprincerealty.com',
    logo: null,
    paidContact: false,
  },
  'liberty-agency': {
    name: 'Liberty Agency',
    domain: 'agence-liberty.com',
    logo: 'https://www.agence-liberty.com/images/favicon.png',
    paidContact: false,
  },
  lienhard: { name: 'Lienhard Immo', domain: 'lienhardimmo.fr', logo: null, paidContact: false },
  locservice: { name: 'LocService', domain: null, logo: null, paidContact: true },
  lodgis: { name: 'Lodgis', domain: null, logo: null, paidContact: false },
  'lt-immobilier': {
    name: 'LT Immobilier',
    domain: 'lt-immobilier.com',
    logo: 'https://www.lt-immobilier.com/images/favicon.png',
    paidContact: false,
  },
  lumina: { name: 'Lumina Immobilier', domain: 'lumina-immo.fr', logo: null, paidContact: false },
  'maison-quatre': {
    name: 'Maison Quatre',
    domain: 'maisonquatre.la-boite-immo.com',
    logo: 'https://maisonquatre.la-boite-immo.com/images/favicon.png',
    paidContact: false,
  },
  marcele: {
    name: 'Marcele Immobilier',
    domain: 'ballestri-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'massena-immo': {
    name: 'Masséna Immobilier',
    domain: 'massena-immo.com',
    logo: null,
    paidContact: false,
  },
  'mediterranee-immo': {
    name: 'Méditerranée Immo',
    domain: 'mediterranee-immo.fr',
    logo: null,
    paidContact: false,
  },
  midem: {
    name: 'Midem Immobilier',
    domain: 'midem-immobilier.fr',
    logo: 'https://www.midem-immobilier.fr/images/favicon.png',
    paidContact: false,
  },
  mirabello: {
    name: 'Mirabello Immobilier',
    domain: 'mirabello-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'mk-immo': { name: 'MK Immo', domain: 'mk-immo.fr', logo: null, paidContact: false },
  murta: {
    name: 'Murta Immobilier',
    domain: 'murta-immobilier.com',
    logo: 'https://www.murta-immobilier.com/images/favicon.png',
    paidContact: false,
  },
  'nice-premium': {
    name: 'Nice Premium Immobilier',
    domain: 'nice-premium-immobilier.com',
    logo: null,
    paidContact: false,
  },
  nousgerons: { name: 'NousGérons', domain: 'nousgerons.com', logo: null, paidContact: false },
  optimmo: { name: 'Optimmo', domain: 'groupe-optimmo.fr', logo: null, paidContact: false },
  orea: { name: 'Oréa Immobilier', domain: 'orea-immobilier.fr', logo: null, paidContact: false },
  orpi: { name: 'Orpi', domain: null, logo: null, paidContact: false },
  'palais-immobilier': {
    name: 'Palais Immobilier',
    domain: 'palaisimmobilier.com',
    logo: null,
    paidContact: false,
  },
  pap: { name: 'PAP', domain: null, logo: null, paidContact: false },
  'partners-immo': {
    name: 'Partners Immo',
    domain: 'partners-immo.fr',
    logo: null,
    paidContact: false,
  },
  paruvendu: { name: 'ParuVendu', domain: null, logo: null, paidContact: false },
  personalimmo: {
    name: 'Personal Immo',
    domain: 'personalimmo.fr',
    logo: null,
    paidContact: false,
  },
  'pht-real-estate': {
    name: 'PHT Real Estate',
    domain: 'phtrealestate.com',
    logo: null,
    paidContact: false,
  },
  postillon: {
    name: 'Postillon Immobilier',
    domain: 'postillon-immobilier.fr',
    logo: null,
    paidContact: false,
  },
  privilege: {
    name: 'Agence Privilège',
    domain: 'agenceprivilege.com',
    logo: null,
    paidContact: false,
  },
  procivis: { name: 'Immo de France (Procivis)', domain: null, logo: null, paidContact: false },
  provencalpes: { name: 'Provencalpes', domain: 'provencalpes.fr', logo: null, paidContact: false },
  pujol: {
    name: 'Immobilière Pujol',
    domain: 'immobiliere-pujol.fr',
    logo: null,
    paidContact: false,
  },
  rentumo: { name: 'Rentumo', domain: null, logo: null, paidContact: true },
  'reussite-immo': {
    name: 'Réussite Immo Nice',
    domain: 'immonice06.fr',
    logo: null,
    paidContact: false,
  },
  'reutter-invest': {
    name: 'Reutter Invest',
    domain: 'reutterinvest.fr',
    logo: null,
    paidContact: false,
  },
  'riviera-concept': {
    name: 'Riviera Concept',
    domain: 'rivieraconcept.com',
    logo: 'https://www.rivieraconcept.com/images/favicon.png',
    paidContact: false,
  },
  roseland: {
    name: 'Immobilière Roseland',
    domain: 'immobiliereroseland.fr',
    logo: 'https://www.immobiliereroseland.fr/images/favicon.png',
    paidContact: false,
  },
  safi: {
    name: 'SAFI Méditerranée',
    domain: 'safimediterranee.fr',
    logo: null,
    paidContact: false,
  },
  'sag-immobilier': {
    name: 'SAG Immobilier',
    domain: 'sag-immobilier.com',
    logo: null,
    paidContact: false,
  },
  'saint-roch': {
    name: 'Saint Roch Immobilier',
    domain: 'saintrochimmobilier.com',
    logo: 'https://saintrochimmobilier.com/images/favicon.ico',
    paidContact: false,
  },
  sambroni: {
    name: 'Sambroni Immobilier',
    domain: 'agencesambroni.com',
    logo: null,
    paidContact: false,
  },
  'savi-esteve': {
    name: 'Agence Savi Estève',
    domain: 'saviesteve-nice.com',
    logo: null,
    paidContact: false,
  },
  studapart: { name: 'Studapart', domain: null, logo: null, paidContact: false },
  'sud-contact': {
    name: 'Sud Contact Immobilier',
    domain: 'nice-ouest-immobilier.com',
    logo: 'https://www.nice-ouest-immobilier.com/images/favicon.png',
    paidContact: false,
  },
  'victor-hugo': {
    name: 'Immobilière Victor Hugo',
    domain: 'immobilierevictorhugo.fr',
    logo: null,
    paidContact: false,
  },
  vizcaya: { name: 'Vizcaya Immobilier', domain: 'vizcaya.fr', logo: null, paidContact: false },
  'votre-agence-immo': {
    name: 'Votre Agence Immo',
    domain: 'votre-agence-immo.fr',
    logo: null,
    paidContact: false,
  },
  winter: {
    name: 'Winter Immobilier',
    domain: 'agence-winter.com',
    logo: 'https://www.agence-winter.com/favicons/favicon.ico',
    paidContact: false,
  },
};
