/**
 * ENGENDRÉ — ne pas modifier à la main.
 * Reconstruire avec `pnpm --filter @maioun/frontend run sources`.
 *
 * La table des sources, telle que le collecteur les déclare : un nom lisible et,
 * pour les agences qui ont leur propre site, son domaine.
 *
 * `domain` vaut `null` pour les portails : leur domaine n'est pas celui d'une
 * agence, et s'en servir comme logo donnerait la même image à des dizaines
 * d'agences distinctes.
 *
 * `logo` n'est renseigné que pour les agences dont l'icône N'EST PAS à
 * `/favicon.ico` — c'est l'adresse que leur site déclare lui-même.
 *
 * `paidContact` marque les sources qui FONT PAYER la mise en relation :
 * l'écran le dit avant le clic, plutôt que de laisser découvrir le péage.
 *
 * `address` est l'adresse de vitrine que l'agence publie, quand on la connaît.
 */

export interface SourceInfo {
  readonly name: string;
  readonly domain: string | null;
  readonly logo: string | null;
  /** La source vend la mise en relation : ses coordonnées ne sont pas libres. */
  readonly paidContact: boolean;
  /** Adresse de la vitrine de l'agence, telle qu'elle la publie. */
  readonly address: {
    readonly street: string;
    readonly postalCode: string;
    readonly city: string;
  } | null;
}

export const SOURCES: Readonly<Record<string, SourceInfo>> = {
  'aa-gestion': {
    name: 'AA Gestion',
    domain: 'aagestion.net',
    logo: 'https://www.aagestion.net/images/favicon.png',
    paidContact: false,
    address: { street: '3 boulevard du Parc Impérial', postalCode: '06000', city: 'Nice' },
  },
  'abyla-bosse': {
    name: 'Abyla Bosse',
    domain: 'immobiliere-abc.com',
    logo: null,
    paidContact: false,
    address: { street: '4 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  acetimo: {
    name: 'Acetimo',
    domain: 'acetimo.com',
    logo: null,
    paidContact: false,
    address: { street: '1 avenue Mirabeau', postalCode: '06000', city: 'Nice' },
  },
  'acropolis-immo': {
    name: 'Acropolis Immobilier',
    domain: 'acropolisimmo.com',
    logo: null,
    paidContact: false,
    address: { street: '47 rue Arson', postalCode: '06300', city: 'Nice' },
  },
  afedim: { name: 'AFEDIM', domain: 'afedim.fr', logo: null, paidContact: false, address: null },
  'agence-5-promenade': {
    name: 'Agence 5 Promenade',
    domain: '5promenade.fr',
    logo: null,
    paidContact: false,
    address: { street: '5 promenade des Anglais', postalCode: '06000', city: 'Nice' },
  },
  'agence-azureenne': {
    name: 'L’Agence Azuréenne',
    domain: 'lagenceazureenne.com',
    logo: 'https://www.lagenceazureenne.com/images/favicon.png',
    paidContact: false,
    address: { street: '157 avenue de Nice', postalCode: '06800', city: 'Cagnes-sur-Mer' },
  },
  'agence-californie': {
    name: 'Agence Californie',
    domain: 'agencecalifornie.fr',
    logo: null,
    paidContact: false,
    address: { street: '229 avenue de la Californie', postalCode: '06200', city: 'Nice' },
  },
  'agence-castel': {
    name: 'Agence Castel',
    domain: 'agencecastel.com',
    logo: null,
    paidContact: false,
    address: { street: '25 rue Bonaparte', postalCode: '06300', city: 'Nice' },
  },
  'agence-des-domaines': {
    name: 'Agence des Domaines',
    domain: 'agencedesdomaines.com',
    logo: 'https://www.agencedesdomaines.com/images/favicon.png',
    paidContact: false,
    address: { street: '57 avenue de la Gare', postalCode: '06800', city: 'Cagnes-sur-Mer' },
  },
  'agence-du-centre': {
    name: 'Agence du Centre',
    domain: 'agenceducentrenice.com',
    logo: 'https://www.agenceducentrenice.com/images/favicon.png',
    paidContact: false,
    address: null,
  },
  'agence-du-port': {
    name: 'Agence du Port de Nice',
    domain: 'agenceduportdenice.fr',
    logo: null,
    paidContact: false,
    address: { street: '28 boulevard Stalingrad', postalCode: '06300', city: 'Nice' },
  },
  'agence-dumas': {
    name: 'Agence Dumas',
    domain: 'agencedumas.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'agence-longchamp': {
    name: 'Agence Longchamp',
    domain: 'agencelongchamp.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'agence-passy': {
    name: 'Agence Passy',
    domain: 'agencepassy.com',
    logo: 'https://www.agencepassy.com/favicon.png',
    paidContact: false,
    address: { street: '4 place Franklin', postalCode: '06000', city: 'Nice' },
  },
  'agence-riviera': {
    name: 'Agence Riviera Real Estate',
    domain: 'agenceriviera.com',
    logo: null,
    paidContact: false,
    address: { street: '12 rue Cassini', postalCode: '06300', city: 'Nice' },
  },
  'agence-victoire': {
    name: 'Agence de la Victoire',
    domain: 'agence-victoire-nice.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'agent-nicois': {
    name: "L'Agent Niçois",
    domain: 'agentnicois.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  agir: {
    name: 'Cabinet A.G.I.R.',
    domain: 'agir.immo',
    logo: 'https://www.agir.immo/images/favicon.png',
    paidContact: false,
    address: { street: '2 rue Maréchal Joffre', postalCode: '06000', city: 'Nice' },
  },
  akorimmo: {
    name: 'AKOR Immo',
    domain: 'akorimmo.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  alberti: {
    name: 'Alberti Immobilier',
    domain: 'agencealbertinice.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'alliance-conseil': {
    name: 'A Alliance Conseil Immobilier',
    domain: 'allianceconseilimmo.com',
    logo: null,
    paidContact: false,
    address: { street: '3 rue Auguste Gal', postalCode: '06300', city: 'Nice' },
  },
  'altarea-nice': {
    name: 'Altarea Gestion Immobilière - Nice',
    domain: 'altarea.flatbay.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'am-concept': {
    name: 'AM Concept Patrimoine Immobilier',
    domain: 'amconcept.immo',
    logo: null,
    paidContact: false,
    address: null,
  },
  'ang-immobilier': {
    name: 'ANG Immobilier',
    domain: 'agence-nice-gambetta.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'aparte-immobilier': {
    name: 'Aparté Immobilier',
    domain: 'aparte-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '47 rue Rossini', postalCode: '06000', city: 'Nice' },
  },
  'api-nice': {
    name: 'API Nice (Azur Patrimoine Immobilier)',
    domain: 'agence-api.com',
    logo: 'https://www.agence-api.com/images/favicon.png',
    paidContact: false,
    address: { street: '3 rue Bavastro', postalCode: '06300', city: 'Nice' },
  },
  arthurimmo: {
    name: 'Arthurimmo.com Nice',
    domain: null,
    logo: null,
    paidContact: false,
    address: null,
  },
  'ashley-parker': {
    name: 'Ashley & Parker',
    domain: 'ashley-parker.fr',
    logo: null,
    paidContact: false,
    address: { street: '39 rue de France', postalCode: '06000', city: 'Nice' },
  },
  aurus: {
    name: 'Aurus Immobilier',
    domain: 'aurusimmo.com',
    logo: 'https://www.aurusimmo.com/images/favicon.png',
    paidContact: false,
    address: { street: '14 rue du Maréchal Joffre', postalCode: '06310', city: 'Beaulieu-sur-Mer' },
  },
  'azur-conseil-salmon': {
    name: 'Azur Conseil Salmon',
    domain: 'acsimmo.fr',
    logo: 'https://www.acsimmo.fr/images/favicon.png',
    paidContact: false,
    address: { street: '26 boulevard de Cessole', postalCode: '06100', city: 'Nice' },
  },
  azurimmo: {
    name: 'Azurimmo',
    domain: 'azurimmo06.net',
    logo: null,
    paidContact: false,
    address: { street: '170 boulevard Napoléon III', postalCode: '06200', city: 'Nice' },
  },
  'barbera-gestion': {
    name: 'Barbera Gestion & Patrimoine',
    domain: 'barbera-gestion.com',
    logo: null,
    paidContact: false,
    address: { street: '29 avenue Jean Médecin', postalCode: '06000', city: 'Nice' },
  },
  bbii: { name: 'BBii', domain: 'bbii.fr', logo: null, paidContact: false, address: null },
  beaumont: {
    name: 'Beaumont Immobilier',
    domain: 'beaumontimmo.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  belgravia: {
    name: 'Belgravia',
    domain: 'belgravia.fr',
    logo: 'https://www.belgravia.fr/images/favicon.png',
    paidContact: false,
    address: { street: '54 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  bep: {
    name: 'BEP Logement',
    domain: 'bep-logement.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'bep-abonnes': {
    name: 'BEP Logement (abonné)',
    domain: null,
    logo: null,
    paidContact: false,
    address: null,
  },
  berenice: {
    name: 'Bérénice Immobilier',
    domain: 'berenice-immobilier.com',
    logo: 'https://www.berenice-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
  },
  bienici: { name: 'Bien’ici', domain: null, logo: null, paidContact: false, address: null },
  'blue-residences': {
    name: 'Blue Résidences',
    domain: 'blue-residences.fr',
    logo: null,
    paidContact: false,
    address: { street: '4 boulevard de Cimiez', postalCode: '06000', city: 'Nice' },
  },
  bomarche: {
    name: 'BôMarché by Lambda Immobilier',
    domain: 'bomarche.fr',
    logo: null,
    paidContact: false,
    address: { street: '14 avenue Borriglione', postalCode: '06000', city: 'Nice' },
  },
  'borne-delaunay': {
    name: 'Borne & Delaunay',
    domain: 'borne-delaunay.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'cabinet-central-gestion': {
    name: 'Cabinet Central Gestion',
    domain: 'immobilier-cabinetcentral.fr',
    logo: null,
    paidContact: false,
    address: { street: '24 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  'cabinet-cordier': {
    name: 'Cabinet Cordier',
    domain: 'cabinetcordier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'cabinet-europazur': {
    name: 'Cabinet Europazur',
    domain: 'europazur.fr',
    logo: null,
    paidContact: false,
    address: { street: '9 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  'cabinet-ledeux': {
    name: 'Cabinet Ledeux Immobilier',
    domain: 'cabinetledeux.com',
    logo: 'https://www.cabinetledeux.com/images/favicon.png',
    paidContact: false,
    address: { street: '15 rue Cassini', postalCode: '06300', city: 'Nice' },
  },
  'cabinet-nardi': {
    name: 'Cabinet Nardi',
    domain: 'cabinetnardi.com',
    logo: 'https://www.cabinetnardi.com/images/favicon.png',
    paidContact: false,
    address: { street: '11 rue Gubernatis', postalCode: '06000', city: 'Nice' },
  },
  'cabinet-reynier': {
    name: 'Cabinet Reynier',
    domain: 'cabinet-reynier.com',
    logo: null,
    paidContact: false,
    address: { street: '78 boulevard Napoléon III', postalCode: '06200', city: 'Nice' },
  },
  'cabinet-ventura': {
    name: 'Cabinet Ventura',
    domain: 'cabinetventura.com',
    logo: null,
    paidContact: false,
    address: { street: '61 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  'cap-sud-immobilier': {
    name: 'Cap Sud Immobilier',
    domain: 'capsud-immobilier.fr',
    logo: null,
    paidContact: false,
    address: { street: '256 avenue de la Californie', postalCode: '06200', city: 'Nice' },
  },
  carletta: {
    name: 'Carletta Immobilier',
    domain: 'carletta.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'cdc-immobilier': {
    name: 'CDC Immobilier',
    domain: 'cdcimmobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '2 place Wilson', postalCode: '06000', city: 'Nice' },
  },
  'cds-gestion': {
    name: 'CDS Gestion',
    domain: 'cdsgestion.fr',
    logo: null,
    paidContact: false,
    address: { street: '51 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  cegestim: {
    name: 'Cegestim',
    domain: 'cegestim.fr',
    logo: null,
    paidContact: false,
    address: { street: '8 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  centragence: {
    name: 'Centragence',
    domain: 'centragence.net',
    logo: null,
    paidContact: false,
    address: null,
  },
  century21: { name: 'Century 21', domain: null, logo: null, paidContact: false, address: null },
  'cimiez-boulevard': {
    name: 'Cimiez Boulevard',
    domain: 'cimiez-boulevard.fr',
    logo: 'https://cimiez-boulevard.fr/build/assets/apple-icon-57x57-C4C4tfzi.png',
    paidContact: false,
    address: null,
  },
  citya: { name: 'Citya Immobilier', domain: null, logo: null, paidContact: false, address: null },
  climmo: {
    name: 'CL Immo Gestion',
    domain: 'climmo.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  coccimmo: {
    name: 'Coccimmo',
    domain: 'coccimmo.com',
    logo: null,
    paidContact: false,
    address: { street: '143 boulevard René Cassin', postalCode: '06200', city: 'Nice' },
  },
  'concept-patrimoine': {
    name: 'Concept Patrimoine Immobilier',
    domain: 'conceptpatrimoine.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  contesso: {
    name: 'Orpi Agence Contesso',
    domain: 'agence-contesso.com',
    logo: 'https://www.agence-contesso.com/images/favicon.png',
    paidContact: false,
    address: { street: '5 avenue des Cigales', postalCode: '06510', city: 'Carros' },
  },
  coprogestimmo: {
    name: 'Coprogestimmo',
    domain: 'coprogestimmo.fr',
    logo: 'https://www.coprogestimmo.fr/images/favicon.png',
    paidContact: false,
    address: null,
  },
  'cote-dazur-properties': {
    name: "Côte d'Azur Properties",
    domain: 'immobilierniceouest.com',
    logo: null,
    paidContact: false,
    address: { street: '2 boulevard Carlone', postalCode: '06200', city: 'Nice' },
  },
  'cote-village': {
    name: 'Immobilier Côté Village',
    domain: 'immobilier-cote-village.com',
    logo: 'https://www.immobilier-cote-village.com/images/favicon.png',
    paidContact: false,
    address: { street: '112 boulevard Général de Gaulle', postalCode: '06340', city: 'La Trinité' },
  },
  'crouzet-breil': {
    name: 'Cabinet Crouzet & Breil',
    domain: 'crouzet-breil.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  dazur: {
    name: "D'Azur Immobilier",
    domain: 'dazur.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'de-vita': {
    name: 'De Vita Immobilier',
    domain: 'devita.immo',
    logo: 'https://www.devita.immo/images/favicon.png',
    paidContact: false,
    address: { street: '52 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  'delta-promotion': {
    name: 'Delta Promotion',
    domain: 'delta-promotion.com',
    logo: 'https://www.delta-promotion.com/images/favicon.png',
    paidContact: false,
    address: { street: '29 rue Pastorelli', postalCode: '06000', city: 'Nice' },
  },
  dgimmo: { name: 'DG Immo', domain: 'dgimmo.fr', logo: null, paidContact: false, address: null },
  difimmo: {
    name: 'Diffusion Immobilière',
    domain: 'difimmo.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  dinamy: {
    name: 'Dinamy Immobilier',
    domain: 'dinamyimmobilier.com',
    logo: 'https://dinamyimmobilier.com/Vues/Images/favicon.jpg',
    paidContact: false,
    address: { street: '13 rue François Guisol', postalCode: '06300', city: 'Nice' },
  },
  'domi-nice-immobilier': {
    name: 'Domi Nice Immobilier',
    domain: 'dominiceimmobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '24 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  drago: {
    name: 'Cabinet Drago',
    domain: 'cabinet-drago.com',
    logo: null,
    paidContact: false,
    address: { street: '29 rue Pastorelli', postalCode: '06000', city: 'Nice' },
  },
  elitimo: {
    name: 'Elitimo',
    domain: 'elitimo.com',
    logo: null,
    paidContact: false,
    address: { street: '7 rue de Rivoli', postalCode: '06000', city: 'Nice' },
  },
  'email-alerts': {
    name: 'Alertes e-mail',
    domain: null,
    logo: null,
    paidContact: false,
    address: null,
  },
  englimmo: {
    name: 'Englimmo',
    domain: 'englimmo.com',
    logo: 'https://www.englimmo.com/images/favicon.png',
    paidContact: false,
    address: { street: '165 avenue de la Californie', postalCode: '06200', city: 'Nice' },
  },
  era: { name: 'ERA Immobilier', domain: null, logo: null, paidContact: false, address: null },
  'eric-immo': {
    name: 'Eric Immo',
    domain: 'eric-immo.com',
    logo: null,
    paidContact: false,
    address: { street: '173 boulevard de la Madeleine', postalCode: '06000', city: 'Nice' },
  },
  'etude-des-vosges': {
    name: 'Étude des Vosges',
    domain: 'etudedesvosges.fr',
    logo: null,
    paidContact: false,
    address: { street: '3 avenue de Saint-Sylvestre', postalCode: '06100', city: 'Nice' },
  },
  'etude-lotte': {
    name: 'Étude Lotte',
    domain: 'etudelotte.com',
    logo: null,
    paidContact: false,
    address: { street: '36 avenue Paul Arène', postalCode: '06000', city: 'Nice' },
  },
  'fds-carre-dor': {
    name: 'FDS Immobilier Carré d’Or',
    domain: 'fdscarredor.com',
    logo: null,
    paidContact: false,
    address: { street: '53 rue de France', postalCode: '06000', city: 'Nice' },
  },
  ferrero: {
    name: 'Agence Ferrero',
    domain: 'ferrero-immobilier.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'figaro-immo': {
    name: 'Figaro Immobilier',
    domain: null,
    logo: null,
    paidContact: false,
    address: null,
  },
  'fit-immobilier': {
    name: 'FIT Immobilier',
    domain: 'fit-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '1 avenue de la Lanterne', postalCode: '06200', city: 'Nice' },
  },
  'five-stars': {
    name: '5 Stars Holiday House',
    domain: 'fivestarsholidayhouserealestate.com',
    logo: null,
    paidContact: false,
    address: { street: '40 rue de la Buffa', postalCode: '06000', city: 'Nice' },
  },
  fnaim: { name: 'FNAIM', domain: null, logo: null, paidContact: false, address: null },
  foncia: { name: 'Foncia', domain: null, logo: null, paidContact: false, address: null },
  forimmo: {
    name: 'Forimmo',
    domain: 'forimmo.fr',
    logo: null,
    paidContact: false,
    address: { street: '31 ter rue Barla', postalCode: '06300', city: 'Nice' },
  },
  'french-riviera-studios': {
    name: 'French Riviera Studios',
    domain: 'studios-nice.com',
    logo: null,
    paidContact: false,
    address: { street: '2 place Magenta', postalCode: '06000', city: 'Nice' },
  },
  'gestion-casa-immo': {
    name: 'Gestion Casa Immobilière',
    domain: 'gestion-casa-immo.com',
    logo: 'https://www.gestion-casa-immo.com/images/favicon.png',
    paidContact: false,
    address: { street: '49 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  'gestion-cassini': {
    name: 'Gestion Cassini',
    domain: 'gestioncassini.com',
    logo: null,
    paidContact: false,
    address: { street: '12 rue François Guisol', postalCode: '06300', city: 'Nice' },
  },
  gestymo: {
    name: 'Gestymo',
    domain: 'gestymo.com',
    logo: 'https://www.gestymo.com/images/favicon.png',
    paidContact: false,
    address: { street: '375 promenade des Anglais', postalCode: '06200', city: 'Nice' },
  },
  giletta: {
    name: 'Giletta Immobilier',
    domain: 'giletta-properties.com',
    logo: 'https://www.giletta-properties.com/images/favicon.png',
    paidContact: false,
    address: { street: '1 rue Maurice Jaubert', postalCode: '06000', city: 'Nice' },
  },
  'grand-metropole': {
    name: 'Grand Métropole',
    domain: 'gdmetropole.com',
    logo: null,
    paidContact: false,
    address: { street: '8 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  griguer: {
    name: 'Cabinet Griguer',
    domain: 'griguer-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'groupe-foch': {
    name: 'Foch Immobilier',
    domain: 'groupe-foch.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'groupe-marshall': {
    name: 'Groupe Marshall',
    domain: 'cabinet-marshall.com',
    logo: 'https://www.cabinet-marshall.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 rue de la Liberté', postalCode: '06000', city: 'Nice' },
  },
  'groupe-picado': {
    name: 'Groupe Picado',
    domain: 'groupepicado.com',
    logo: null,
    paidContact: false,
    address: { street: '12 avenue Malausséna', postalCode: '06000', city: 'Nice' },
  },
  'home-on-riviera': {
    name: 'Home on Riviera',
    domain: 'homeonriviera.com',
    logo: null,
    paidContact: false,
    address: { street: '3 rue Cronstadt', postalCode: '06000', city: 'Nice' },
  },
  'home-pearl': {
    name: 'Home Pearl',
    domain: 'homepearl.immo',
    logo: null,
    paidContact: false,
    address: { street: '16 rue Foncet', postalCode: '06000', city: 'Nice' },
  },
  'ici-immobilier': {
    name: 'I.C.I Info Conseil Immobilier',
    domain: 'ici-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  igti: {
    name: 'Immobilière GTI',
    domain: 'immobilieregti.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'immo-3-points': {
    name: 'Immo 3 Points',
    domain: 'immo3points.fr',
    logo: null,
    paidContact: false,
    address: { street: '1 rue Alberti', postalCode: '06000', city: 'Nice' },
  },
  'immo-consult-cote-sud': {
    name: 'Immo Consult Côté Sud',
    domain: 'immoconsultcotesud.com',
    logo: 'https://www.immoconsultcotesud.com/images/favicon.png',
    paidContact: false,
    address: { street: '72 avenue d’Estienne d’Orves', postalCode: '06000', city: 'Nice' },
  },
  'immo-ideal': {
    name: 'Immo Idéal',
    domain: 'immo-ideal.fr',
    logo: null,
    paidContact: false,
    address: { street: '24 avenue de Saint-Sylvestre', postalCode: '06100', city: 'Nice' },
  },
  'immo-jbf': {
    name: 'Immo JBF',
    domain: 'immo-jbf.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'immo-sud': {
    name: 'Immo-Sud Nice',
    domain: 'agenceimmosud.com',
    logo: 'https://www.agenceimmosud.com/images/favicon.png',
    paidContact: false,
    address: null,
  },
  immo3000: {
    name: 'Immo 3000',
    domain: 'immo3000.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  immobilier2nice: {
    name: 'Immobilier 2 Nice',
    domain: 'immobilier2nice.com',
    logo: null,
    paidContact: false,
    address: { street: '1 boulevard Auguste Raynaud', postalCode: '06100', city: 'Nice' },
  },
  'immobiliere-camo': {
    name: 'Immobilière Camo',
    domain: 'immobiliere-camo.fr',
    logo: null,
    paidContact: false,
    address: { street: '26 rue Arson', postalCode: '06300', city: 'Nice' },
  },
  'immobiliere-nicoise': {
    name: "L'Immobilière Niçoise",
    domain: 'immobiliere-nicoise.com',
    logo: 'https://www.immobiliere-nicoise.com/images/favicon.png',
    paidContact: false,
    address: { street: '33 avenue du Maréchal Foch', postalCode: '06000', city: 'Nice' },
  },
  'immobiliere-pelou': {
    name: 'Immobilière Pelou',
    domain: 'immobiliere-pelou.com',
    logo: 'https://www.immobiliere-pelou.com/images/favicon.png',
    paidContact: false,
    address: null,
  },
  imodirect: {
    name: 'Imodirect',
    domain: 'annonces.imodirect.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  inli: { name: "In'li", domain: 'inli.fr', logo: null, paidContact: false, address: null },
  'isit-immobilier': {
    name: 'ISIT Immobilier',
    domain: 'isitimmo.com',
    logo: null,
    paidContact: false,
    address: { street: '26 rue de la Buffa', postalCode: '06000', city: 'Nice' },
  },
  'joseph-garnier': {
    name: 'Joseph Garnier Real Estate',
    domain: 'josephgarnier.fr',
    logo: null,
    paidContact: false,
    address: { street: '6 boulevard Joseph Garnier', postalCode: '06000', city: 'Nice' },
  },
  'kalliste-immo-conseil': {
    name: 'Kalliste Immo Conseil',
    domain: 'kalliste-immo-conseil.com',
    logo: null,
    paidContact: false,
    address: { street: '27 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  kapera: {
    name: 'Kapera Immobilier',
    domain: 'kapera-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'la-chouette': {
    name: 'La Chouette Agence Immobilière',
    domain: 'lachouette.immo',
    logo: 'https://www.lachouette.immo/images/favicon.png',
    paidContact: false,
    address: { street: '3 place Pellegrini', postalCode: '06300', city: 'Nice' },
  },
  'la-clef-immobiliere': {
    name: 'La Clef Immobilière',
    domain: 'laclefimmobiliere.com',
    logo: 'https://www.laclefimmobiliere.com/images/favicon.png',
    paidContact: false,
    address: { street: '24 boulevard Saint-Roch', postalCode: '06300', city: 'Nice' },
  },
  'la-conca-dor': {
    name: 'La Conca d’Or',
    domain: 'laconcador.com',
    logo: null,
    paidContact: false,
    address: { street: '466 boulevard Léon Sauvan', postalCode: '06690', city: 'Tourrette-Levens' },
  },
  'la-firme': {
    name: 'La Firme',
    domain: 'proazurdagasso.com',
    logo: null,
    paidContact: false,
    address: { street: '12 rue Gioffredo', postalCode: '06000', city: 'Nice' },
  },
  'la-franco-suisse': {
    name: 'La Franco Suisse',
    domain: 'lafrancosuisse.com',
    logo: null,
    paidContact: false,
    address: { street: "19 rue de l'Hôtel des Postes", postalCode: '06000', city: 'Nice' },
  },
  'la-perouse': {
    name: 'La Pérouse Immobilier',
    domain: 'laperouse-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '17 rue Alfred Mortier', postalCode: '06000', city: 'Nice' },
  },
  'la-petite-maison': {
    name: 'La Petite Maison',
    domain: 'la-petitemaison.fr',
    logo: null,
    paidContact: false,
    address: { street: '301 chemin de la Ginestière', postalCode: '06200', city: 'Nice' },
  },
  ladresse: {
    name: "L'Adresse",
    domain: 'ladresse.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  laforet: { name: 'Laforêt', domain: null, logo: null, paidContact: false, address: null },
  'lagence-jean-jaures': {
    name: 'L’Agence Jean Jaurès',
    domain: 'l-agence.fr',
    logo: 'https://www.l-agence.fr/images/favicon.png',
    paidContact: false,
    address: { street: '48 boulevard Jean Jaurès', postalCode: '06300', city: 'Nice' },
  },
  lamy: { name: 'Lamy Immobilier', domain: null, logo: null, paidContact: false, address: null },
  lapierre: {
    name: 'Anne-Sophie Lapierre Immobilier',
    domain: 'lapierre-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'lb-immobilier': {
    name: 'L&B Immobilier',
    domain: 'lb-immobilier.fr',
    logo: 'https://www.lb-immobilier.fr/images/favicon.png',
    paidContact: false,
    address: { street: '4 avenue de Verdun', postalCode: '06000', city: 'Nice' },
  },
  'leprince-realty': {
    name: 'leprince realty',
    domain: 'leprincerealty.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'liberty-agency': {
    name: 'Liberty Agency',
    domain: 'agence-liberty.com',
    logo: 'https://www.agence-liberty.com/images/favicon.png',
    paidContact: false,
    address: { street: '136 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
  },
  lienhard: {
    name: 'Lienhard Immo',
    domain: 'lienhardimmo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  locservice: { name: 'LocService', domain: null, logo: null, paidContact: true, address: null },
  lodgis: { name: 'Lodgis', domain: null, logo: null, paidContact: false, address: null },
  loquis: {
    name: 'Cabinet Loquis',
    domain: 'loquis.fr',
    logo: null,
    paidContact: false,
    address: { street: '3 place Alexandre Médecin', postalCode: '06100', city: 'Nice' },
  },
  'lt-immobilier': {
    name: 'LT Immobilier',
    domain: 'lt-immobilier.com',
    logo: 'https://www.lt-immobilier.com/images/favicon.png',
    paidContact: false,
    address: null,
  },
  lumina: {
    name: 'Lumina Immobilier',
    domain: 'lumina-immo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'maison-k': {
    name: 'Maison K Immobilier',
    domain: 'maisonk-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '3 place Masséna', postalCode: '06000', city: 'Nice' },
  },
  'maison-quatre': {
    name: 'Maison Quatre',
    domain: 'maisonquatre.la-boite-immo.com',
    logo: 'https://maisonquatre.la-boite-immo.com/images/favicon.png',
    paidContact: false,
    address: { street: '4 rue Dalpozzo', postalCode: '06000', city: 'Nice' },
  },
  marcele: {
    name: 'Marcele Immobilier',
    domain: 'ballestri-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '2 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  'marchal-immobilier': {
    name: 'Marchal Immobilier',
    domain: 'marchal-immobilier.fr',
    logo: null,
    paidContact: false,
    address: { street: '83 boulevard Gambetta', postalCode: '06000', city: 'Nice' },
  },
  'marro-immobilier': {
    name: 'Cabinet Marro Immobilier',
    domain: 'marro-immobilier.com',
    logo: 'https://www.marro-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '41 boulevard Pierre Sola', postalCode: '06300', city: 'Nice' },
  },
  'massena-immo': {
    name: 'Masséna Immobilier',
    domain: 'massena-immo.com',
    logo: null,
    paidContact: false,
    address: { street: '12 avenue Félix Faure', postalCode: '06000', city: 'Nice' },
  },
  'mediterranee-immo': {
    name: 'Méditerranée Immo',
    domain: 'mediterranee-immo.fr',
    logo: null,
    paidContact: false,
    address: { street: '20 avenue Valombrose', postalCode: '06000', city: 'Nice' },
  },
  midem: {
    name: 'Midem Immobilier',
    domain: 'midem-immobilier.fr',
    logo: 'https://www.midem-immobilier.fr/images/favicon.png',
    paidContact: false,
    address: { street: '8 avenue Saint-Augustin', postalCode: '06200', city: 'Nice' },
  },
  'milor-immobilier': {
    name: 'Milor Immobilier',
    domain: 'milorimmobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '50 boulevard Joseph Garnier', postalCode: '06000', city: 'Nice' },
  },
  mirabello: {
    name: 'Mirabello Immobilier',
    domain: 'mirabello-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  miramar: {
    name: 'Miramar Real Estate',
    domain: 'miramarimmo.com',
    logo: null,
    paidContact: false,
    address: { street: '7/13 boulevard Franck Pilatte', postalCode: '06300', city: 'Nice' },
  },
  'mk-immo': {
    name: 'MK Immo',
    domain: 'mk-immo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'moss-immobilier': {
    name: 'Moss Immobilier',
    domain: 'mossimmobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '2 rue Beethoven', postalCode: '06000', city: 'Nice' },
  },
  murta: {
    name: 'Murta Immobilier',
    domain: 'murta-immobilier.com',
    logo: 'https://www.murta-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '23 bis avenue Général de Gaulle', postalCode: '06340', city: 'Drap' },
  },
  'nestenn-nice-port': {
    name: 'Nestenn Nice Port - Riquier',
    domain: 'immobilier-nice-port.nestenn.com',
    logo: null,
    paidContact: false,
    address: { street: '18 boulevard de Riquier', postalCode: '06300', city: 'Nice' },
  },
  'nice-premium': {
    name: 'Nice Premium Immobilier',
    domain: 'nice-premium-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '21 rue Michel-Ange', postalCode: '06100', city: 'Nice' },
  },
  'nicolas-pisani': {
    name: 'Nicolas Pisani Real Estate',
    domain: 'nicolaspisani.com',
    logo: null,
    paidContact: false,
    address: { street: '1 rue Paul Doumer', postalCode: '06310', city: 'Beaulieu-sur-Mer' },
  },
  norait: {
    name: 'Norait Immobilier',
    domain: 'norait-immobilier.fr',
    logo: null,
    paidContact: false,
    address: { street: '20 rue Verdi', postalCode: '06000', city: 'Nice' },
  },
  nousgerons: {
    name: 'NousGérons',
    domain: 'nousgerons.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  optimmo: {
    name: 'Optimmo',
    domain: 'groupe-optimmo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  orea: {
    name: 'Oréa Immobilier',
    domain: 'orea-immobilier.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'orientation-immobiliere': {
    name: 'L’Orientation Immobilière',
    domain: 'orimnice.fr',
    logo: null,
    paidContact: false,
    address: { street: '76 avenue de Brancolar', postalCode: '06100', city: 'Nice' },
  },
  orpi: { name: 'Orpi', domain: null, logo: null, paidContact: false, address: null },
  'palais-immobilier': {
    name: 'Palais Immobilier',
    domain: 'palaisimmobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  pap: { name: 'PAP', domain: null, logo: null, paidContact: false, address: null },
  'parnasse-immobilier': {
    name: 'Parnasse Immobilier',
    domain: 'parnasse-immobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '10 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  'partners-immo': {
    name: 'Partners Immo',
    domain: 'partners-immo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  paruvendu: { name: 'ParuVendu', domain: null, logo: null, paidContact: false, address: null },
  personalimmo: {
    name: 'Personal Immo',
    domain: 'personalimmo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'phoenix-glv': {
    name: 'Phoenix GLV',
    domain: 'phoenix-glv.com',
    logo: 'https://www.phoenix-glv.com/images/favicon.png',
    paidContact: false,
    address: { street: '455 promenade des Anglais', postalCode: '06200', city: 'Nice' },
  },
  'pht-real-estate': {
    name: 'PHT Real Estate',
    domain: 'phtrealestate.com',
    logo: null,
    paidContact: false,
    address: { street: '15 rue Biscarra', postalCode: '06000', city: 'Nice' },
  },
  'platine-immobilier': {
    name: 'Platine Immobilier',
    domain: 'platineimmobilier.eu',
    logo: 'https://www.platineimmobilier.eu/images/favicon.png',
    paidContact: false,
    address: { street: '5 rue Blacas', postalCode: '06100', city: 'Nice' },
  },
  postillon: {
    name: 'Postillon Immobilier',
    domain: 'postillon-immobilier.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  privilege: {
    name: 'Agence Privilège',
    domain: 'agenceprivilege.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  procivis: {
    name: 'Immo de France Côte d’Azur',
    domain: null,
    logo: null,
    paidContact: false,
    address: null,
  },
  provencalpes: {
    name: 'Provencalpes',
    domain: 'provencalpes.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  pujol: {
    name: 'Immobilière Pujol',
    domain: 'immobiliere-pujol.fr',
    logo: null,
    paidContact: false,
    address: { street: '7 rue du Dr Fiolle', postalCode: '13006', city: 'Marseille' },
  },
  rentumo: { name: 'Rentumo', domain: null, logo: null, paidContact: true, address: null },
  'resid-immo': {
    name: 'Resid’Immo',
    domain: 'residimmo.fr',
    logo: 'https://www.residimmo.fr/images/favicon.png',
    paidContact: false,
    address: { street: '900 boulevard du Mercantour', postalCode: '06200', city: 'Nice' },
  },
  'reussite-immo': {
    name: 'Réussite Immo Nice',
    domain: 'immonice06.fr',
    logo: null,
    paidContact: false,
    address: { street: '6 rue Massenet', postalCode: '06000', city: 'Nice' },
  },
  'reutter-invest': {
    name: 'Reutter Invest',
    domain: 'reutterinvest.fr',
    logo: null,
    paidContact: false,
    address: { street: '45 rue Rossini', postalCode: '06000', city: 'Nice' },
  },
  'richer-immobilier': {
    name: 'Richer Immobilier',
    domain: 'richerimmobilier.com',
    logo: null,
    paidContact: false,
    address: { street: '50 boulevard Stalingrad', postalCode: '06300', city: 'Nice' },
  },
  'riviera-angels': {
    name: 'Riviera Angels Immobilier',
    domain: 'riviera-angels.com',
    logo: null,
    paidContact: false,
    address: { street: '50 rue de France', postalCode: '06000', city: 'Nice' },
  },
  'riviera-concept': {
    name: 'Riviera Concept',
    domain: 'rivieraconcept.com',
    logo: 'https://www.rivieraconcept.com/images/favicon.png',
    paidContact: false,
    address: { street: '67 rue Rossini', postalCode: '06000', city: 'Nice' },
  },
  roseland: {
    name: 'Immobilière Roseland',
    domain: 'immobiliereroseland.fr',
    logo: 'https://www.immobiliereroseland.fr/images/favicon.png',
    paidContact: false,
    address: { street: '38 rue Auguste Gal', postalCode: '06300', city: 'Nice' },
  },
  safi: {
    name: 'SAFI Méditerranée',
    domain: 'safimediterranee.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'sag-immobilier': {
    name: 'SAG Immobilier',
    domain: 'sag-immobilier.com',
    logo: null,
    paidContact: false,
    address: null,
  },
  'saint-roch': {
    name: 'Saint Roch Immobilier',
    domain: 'saintrochimmobilier.com',
    logo: 'https://saintrochimmobilier.com/images/favicon.ico',
    paidContact: false,
    address: null,
  },
  sambroni: {
    name: 'Sambroni Immobilier',
    domain: 'agencesambroni.com',
    logo: null,
    paidContact: false,
    address: { street: '186 avenue de Pessicart', postalCode: '06100', city: 'Nice' },
  },
  'savi-esteve': {
    name: 'Agence Savi Estève',
    domain: 'saviesteve-nice.com',
    logo: null,
    paidContact: false,
    address: { street: '24 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  solissimmo: {
    name: 'Solissimmo',
    domain: 'solissimmo.fr',
    logo: null,
    paidContact: false,
    address: { street: '30 rue Alphonse Karr', postalCode: '06000', city: 'Nice' },
  },
  studapart: { name: 'Studapart', domain: null, logo: null, paidContact: false, address: null },
  'sud-agence': {
    name: 'Sud Agence',
    domain: 'sudagence.fr',
    logo: 'https://www.sudagence.fr/images/favicon.png',
    paidContact: false,
    address: { street: '25 rue Arson', postalCode: '06300', city: 'Nice' },
  },
  'sud-contact': {
    name: 'Sud Contact Immobilier',
    domain: 'nice-ouest-immobilier.com',
    logo: 'https://www.nice-ouest-immobilier.com/images/favicon.png',
    paidContact: false,
    address: { street: '46 avenue Saint-Augustin', postalCode: '06200', city: 'Nice' },
  },
  'sun-immobilia': {
    name: 'Sun Immobilia',
    domain: 'sunimmobilia.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  'tosca-nice-le-port': {
    name: 'Agence Tosca Nice le Port',
    domain: 'agencetosca.com',
    logo: null,
    paidContact: false,
    address: { street: '13 rue Cassini', postalCode: '06300', city: 'Nice' },
  },
  transactimo: {
    name: 'Transactimo',
    domain: 'transactimo-nice.com',
    logo: null,
    paidContact: false,
    address: { street: '19 avenue Georges Clemenceau', postalCode: '06000', city: 'Nice' },
  },
  'valrose-immobilier': {
    name: 'Valrose Immobilier',
    domain: 'valrose-immo.fr',
    logo: null,
    paidContact: false,
    address: { street: '108 avenue Saint-Lambert', postalCode: '06100', city: 'Nice' },
  },
  'victor-hugo': {
    name: 'Immobilière Victor Hugo',
    domain: 'immobilierevictorhugo.fr',
    logo: null,
    paidContact: false,
    address: { street: '15 boulevard Victor Hugo', postalCode: '06000', city: 'Nice' },
  },
  vizcaya: {
    name: 'Vizcaya Immobilier',
    domain: 'vizcaya.fr',
    logo: null,
    paidContact: false,
    address: { street: '4 quai Papacino', postalCode: '06300', city: 'Nice' },
  },
  'votre-agence-immo': {
    name: 'Votre Agence Immo',
    domain: 'votre-agence-immo.fr',
    logo: null,
    paidContact: false,
    address: null,
  },
  westimmo: {
    name: 'Westimmo',
    domain: 'westimmo-properties.com',
    logo: 'https://www.westimmo-properties.com/images/favicon.png',
    paidContact: false,
    address: { street: '200 avenue de la Californie', postalCode: '06200', city: 'Nice' },
  },
  winter: {
    name: 'Winter Immobilier',
    domain: 'agence-winter.com',
    logo: 'https://www.agence-winter.com/favicons/favicon.ico',
    paidContact: false,
    address: null,
  },
};
